#!/usr/bin/env bash
# =============================================================================
# generate-reports.sh — Generate regression test reports
#
# Usage: bash generate-reports.sh <reports_dir>
#
# Reads per-version result directories under <reports_dir>/php-X.Y/ and
# generates three Markdown reports:
#   1. compatibility-report.md   — PHP version compatibility matrix
#   2. developer-fix-report.md   — Deduplicated errors/warnings with fix suggestions
#   3. coverage-report.md        — Code coverage per file, sorted, with highlights
# =============================================================================

set -euo pipefail

REPORTS_DIR="${1:?Usage: generate-reports.sh <reports_dir>}"

# Timestamp for reports
REPORT_DATE=$(date "+%Y-%m-%d %H:%M:%S")

# Discover tested versions (sorted)
VERSIONS=()
for dir in "${REPORTS_DIR}"/php-*/; do
    if [ -d "${dir}" ]; then
        ver=$(basename "${dir}" | sed 's/^php-//')
        VERSIONS+=("${ver}")
    fi
done

# Sort versions
IFS=$'\n' VERSIONS=($(sort -V <<<"${VERSIONS[*]}")); unset IFS

if [ ${#VERSIONS[@]} -eq 0 ]; then
    echo "ERROR: No version result directories found in ${REPORTS_DIR}"
    exit 1
fi

echo "Generating reports for PHP versions: ${VERSIONS[*]}"

# =============================================================================
# Helper: read a field from summary.json (simple grep-based JSON parser)
# =============================================================================
read_json_field() {
    local file="$1"
    local field="$2"
    if [ -f "${file}" ]; then
        grep -o "\"${field}\": *\"\\{0,1\\}[^\",}]*" "${file}" | head -1 | sed 's/.*: *"\{0,1\}//' | sed 's/"\{0,1\}$//'
    else
        echo ""
    fi
}

read_json_int() {
    local file="$1"
    local field="$2"
    local val
    val=$(read_json_field "${file}" "${field}")
    if [[ "${val}" =~ ^-?[0-9]+$ ]]; then
        echo "${val}"
    else
        echo "0"
    fi
}

# =============================================================================
# REPORT 1: Compatibility Report
# =============================================================================
generate_compatibility_report() {
    local output="${REPORTS_DIR}/compatibility-report.md"
    echo "  Generating compatibility report ..."

    cat > "${output}" <<'HEADER'
# PHP Version Compatibility Report

> Auto-generated by the PHP SDK regression test suite.

## Compatibility Matrix

HEADER

    echo "| PHP Version | Composer Install | Tests Run | Tests Passed | Tests Failed | Tests Errors | Tests Skipped | Status |" >> "${output}"
    echo "|:-----------:|:----------------:|:---------:|:------------:|:------------:|:------------:|:-------------:|:------:|" >> "${output}"

    local compatible_versions=""
    local partial_versions=""
    local incompatible_versions=""

    for ver in "${VERSIONS[@]}"; do
        local summary="${REPORTS_DIR}/php-${ver}/summary.json"
        local composer_install
        local tests_run tests_passed tests_failed tests_errors tests_skipped
        local status status_icon composer_icon

        composer_install=$(read_json_field "${summary}" "composer_install")
        tests_run=$(read_json_int "${summary}" "tests_run")
        tests_passed=$(read_json_int "${summary}" "tests_passed")
        tests_failed=$(read_json_int "${summary}" "tests_failed")
        tests_errors=$(read_json_int "${summary}" "tests_errors")
        tests_skipped=$(read_json_int "${summary}" "tests_skipped")
        status=$(read_json_field "${summary}" "status")

        # Composer icon
        case "${composer_install}" in
            pass)   composer_icon="✅ Pass" ;;
            fail)   composer_icon="❌ Fail" ;;
            *)      composer_icon="❓ N/A" ;;
        esac

        # Status icon
        case "${status}" in
            compatible)
                status_icon="✅ Compatible"
                compatible_versions="${compatible_versions} ${ver}"
                ;;
            partial)
                status_icon="⚠️ Partial"
                partial_versions="${partial_versions} ${ver}"
                ;;
            incompatible)
                status_icon="❌ Incompatible"
                incompatible_versions="${incompatible_versions} ${ver}"
                ;;
            build_fail)
                status_icon="❌ Build Failed"
                incompatible_versions="${incompatible_versions} ${ver}"
                ;;
            error)
                status_icon="❌ Error"
                incompatible_versions="${incompatible_versions} ${ver}"
                ;;
            *)
                status_icon="❓ Unknown"
                incompatible_versions="${incompatible_versions} ${ver}"
                ;;
        esac

        # Tests display
        local tests_run_display="${tests_run}"
        local tests_passed_display="${tests_passed}"
        local tests_failed_display="${tests_failed}"
        local tests_errors_display="${tests_errors}"
        local tests_skipped_display="${tests_skipped}"

        if [ "${composer_install}" = "fail" ] || [ "${status}" = "build_fail" ]; then
            tests_run_display="-"
            tests_passed_display="-"
            tests_failed_display="-"
            tests_errors_display="-"
            tests_skipped_display="-"
        fi

        echo "| ${ver} | ${composer_icon} | ${tests_run_display} | ${tests_passed_display} | ${tests_failed_display} | ${tests_errors_display} | ${tests_skipped_display} | ${status_icon} |" >> "${output}"
    done

    # Summary section
    cat >> "${output}" <<EOF

## Summary

- **Report generated**: ${REPORT_DATE}
- **Versions tested**: ${#VERSIONS[@]}
EOF

    if [ -n "${compatible_versions}" ]; then
        echo "- **Compatible**:${compatible_versions}" >> "${output}"
    fi
    if [ -n "${partial_versions}" ]; then
        echo "- **Partially compatible**:${partial_versions}" >> "${output}"
    fi
    if [ -n "${incompatible_versions}" ]; then
        echo "- **Incompatible**:${incompatible_versions}" >> "${output}"
    fi

    # Recommended minimum version
    local min_compatible=""
    for ver in "${VERSIONS[@]}"; do
        local s
        s=$(read_json_field "${REPORTS_DIR}/php-${ver}/summary.json" "status")
        if [ "${s}" = "compatible" ] && [ -z "${min_compatible}" ]; then
            min_compatible="${ver}"
        fi
    done

    if [ -n "${min_compatible}" ]; then
        cat >> "${output}" <<EOF

## Recommendation

Based on the test results, the minimum compatible PHP version is **${min_compatible}**.

\`\`\`json
"require": {
    "php": ">=${min_compatible}"
}
\`\`\`
EOF
    fi

    echo "" >> "${output}"
    echo "---" >> "${output}"
    echo "*Generated by [PHP SDK Regression Test Suite](regression/README.md)*" >> "${output}"
}

# =============================================================================
# REPORT 2: Developer Fix Report
# =============================================================================

# Fix suggestion rules database
# Each rule: PATTERN|SEVERITY|SUGGESTION
# PATTERN is a grep-compatible regex to match error messages
# SEVERITY is: error, warning, deprecation, notice
# SUGGESTION is the recommended fix
declare -a FIX_RULES=(
    # PHP 8.2+ Deprecations
    'strftime\(\)|deprecation|Replace `strftime()` with `IntlDateFormatter` or `date()`. `strftime()` was deprecated in PHP 8.1.\n```php\n// Before\nstrftime("%Y-%m-%d", $timestamp);\n// After\ndate("Y-m-d", $timestamp);\n```'
    'utf8_encode\(\)|deprecation|Replace `utf8_encode()` with `mb_convert_encoding($s, "UTF-8", "ISO-8859-1")`. Deprecated in PHP 8.2.'
    'utf8_decode\(\)|deprecation|Replace `utf8_decode()` with `mb_convert_encoding($s, "ISO-8859-1", "UTF-8")`. Deprecated in PHP 8.2.'
    'Creation of dynamic property|deprecation|Add `#[AllowDynamicProperties]` attribute to the class, or declare the property explicitly.\n```php\n// Option 1: Declare property\nclass Foo {\n    public mixed $bar;\n}\n// Option 2: Use attribute (PHP 8.2+)\n#[AllowDynamicProperties]\nclass Foo {}\n```'
    'Implicit conversion from float.*to int|deprecation|Use explicit `(int)` cast: `$intVal = (int)$floatVal;`'
    'Use of "\${var}" in strings is deprecated|deprecation|Replace `"${var}"` with `"{$var}"` in string interpolation. Deprecated in PHP 8.2.'
    'Passing null to parameter.*of type string|deprecation|Add null coalescing or explicit type cast:\n```php\n// Before\nstrlen($maybeNull);\n// After\nstrlen($maybeNull ?? "");\n```'
    'Optional parameter.*declared before required|deprecation|Reorder parameters so optional ones come after required ones, or remove the default value.'
    'Return type.*should be compatible|deprecation|Update the return type declaration to match the parent class/interface signature.'
    'is deprecated|deprecation|Check the PHP migration guide for the specific deprecation and apply the recommended replacement.'

    # PHP 8.0+ Changes
    'Required parameter.*follows optional|warning|Reorder function parameters: move required parameters before optional ones.'
    'Undefined array key|warning|Check array key existence before access:\n```php\n// Before\n$val = $arr["key"];\n// After\n$val = $arr["key"] ?? null;\n// Or\nif (isset($arr["key"])) { $val = $arr["key"]; }\n```'
    'Undefined variable|warning|Initialize variables before use, or use null coalescing: `$var = $var ?? null;`'
    'Trying to access array offset on.*null|warning|Add null check before array access:\n```php\nif ($data !== null && isset($data["key"])) { ... }\n```'

    # Type errors
    'must be of type|error|Add proper type declarations and ensure correct types are passed. Check the function signature and caller.'
    'Return type of.*must be|error|Add return type declarations to match the interface/parent class:\n```php\n// Before\npublic function count() { ... }\n// After\npublic function count(): int { ... }\n```'
    'cannot be converted to|error|Use explicit type casting or update the code to pass the correct type.'
    'must implement interface|error|Implement all required interface methods with correct signatures.'
    'Declaration of.*must be compatible|error|Update the method signature to match the parent class/interface declaration.'

    # Fatal errors
    'Cannot use.*as default value|error|Use `null` as default and set the value in the constructor body.'
    'Uncaught Error|error|Add proper error handling with try-catch blocks or fix the root cause of the error.'
    'Class.*not found|error|Check autoloading configuration and ensure the class file exists and namespace is correct.'

    # Notices
    'Undefined index|notice|Use `isset()` or null coalescing operator `??` before accessing array indices.'
    'Undefined offset|notice|Check array bounds before access or use `array_key_exists()`.'
    'Trying to get property.*of non-object|notice|Add null check before property access: `if ($obj !== null) { $obj->prop; }`'
)

generate_developer_fix_report() {
    local output="${REPORTS_DIR}/developer-fix-report.md"
    echo "  Generating developer fix report ..."

    # Temporary files for processing
    local tmp_dir="${REPORTS_DIR}/.tmp_fix_report"
    rm -rf "${tmp_dir}"
    mkdir -p "${tmp_dir}"

    # Collect all issues from all versions
    local all_issues="${tmp_dir}/all_issues.txt"
    > "${all_issues}"

    for ver in "${VERSIONS[@]}"; do
        local ver_dir="${REPORTS_DIR}/php-${ver}"

        # Process each issue type
        for issue_type in errors warnings deprecations notices; do
            local issue_file="${ver_dir}/php-${issue_type}.log"
            if [ -f "${issue_file}" ] && [ -s "${issue_file}" ]; then
                while IFS= read -r line; do
                    # Normalize: remove file paths line numbers to group similar issues
                    # Keep the core message for deduplication
                    local normalized
                    normalized=$(echo "${line}" | \
                        sed 's/ in \/[^ ]* on line [0-9]*//g' | \
                        sed 's/ in \/[^ ]*:[0-9]*//g' | \
                        sed 's/on line [0-9]*/on line N/g' | \
                        sed 's/\/app\/workspace\/[^ ]*/FILE/g' | \
                        sed 's/\/app\/source\/[^ ]*/FILE/g' | \
                        sed 's/[0-9]\{1,\}\.[0-9]\{1,\}\.[0-9]\{1,\}/X.Y.Z/g' | \
                        sed 's/  */ /g' | \
                        sed 's/^ *//;s/ *$//')

                    local severity=""
                    case "${issue_type}" in
                        errors)       severity="error" ;;
                        warnings)     severity="warning" ;;
                        deprecations) severity="deprecation" ;;
                        notices)      severity="notice" ;;
                    esac

                    if [ -n "${normalized}" ]; then
                        # Format: severity|version|normalized_message|original_message
                        echo "${severity}|${ver}|${normalized}|${line}" >> "${all_issues}"
                    fi
                done < "${issue_file}"
            fi
        done
    done

    # Deduplicate and count
    local deduped="${tmp_dir}/deduped.txt"
    local counts="${tmp_dir}/counts.txt"

    # Extract unique normalized messages with their severity
    awk -F'|' '{print $1 "|" $3}' "${all_issues}" | sort | uniq -c | sort -rn > "${counts}"

    # Count totals
    local total_error_types=0
    local total_warning_types=0
    local total_deprecation_types=0
    local total_notice_types=0

    while IFS= read -r line; do
        local sev
        sev=$(echo "${line}" | sed 's/^ *[0-9]* *//' | cut -d'|' -f1)
        case "${sev}" in
            error)       total_error_types=$((total_error_types + 1)) ;;
            warning)     total_warning_types=$((total_warning_types + 1)) ;;
            deprecation) total_deprecation_types=$((total_deprecation_types + 1)) ;;
            notice)      total_notice_types=$((total_notice_types + 1)) ;;
        esac
    done < "${counts}"

    local total_unique=$((total_error_types + total_warning_types + total_deprecation_types + total_notice_types))

    # Write report header
    cat > "${output}" <<EOF
# Developer Fix Report

> Auto-generated by the PHP SDK regression test suite.
> Report date: ${REPORT_DATE}

## Summary

- **Total unique issues**: ${total_unique}
- **Errors**: ${total_error_types}
- **Warnings**: ${total_warning_types}
- **Deprecations**: ${total_deprecation_types}
- **Notices**: ${total_notice_types}

EOF

    # Generate sections by severity
    for severity in error warning deprecation notice; do
        local severity_label=""
        local severity_icon=""
        case "${severity}" in
            error)       severity_label="Errors";       severity_icon="❌" ;;
            warning)     severity_label="Warnings";     severity_icon="⚠️" ;;
            deprecation) severity_label="Deprecations"; severity_icon="🔶" ;;
            notice)      severity_label="Notices";      severity_icon="ℹ️" ;;
        esac

        # Get issues of this severity
        local severity_issues="${tmp_dir}/severity_${severity}.txt"
        grep "|${severity}|" "${counts}" > "${severity_issues}" 2>/dev/null || true

        local severity_count
        severity_count=$(wc -l < "${severity_issues}" 2>/dev/null | tr -d ' ')

        if [ "${severity_count}" -eq 0 ]; then
            continue
        fi

        echo "## ${severity_icon} ${severity_label}" >> "${output}"
        echo "" >> "${output}"

        local issue_num=0
        while IFS= read -r count_line; do
            issue_num=$((issue_num + 1))
            local occurrence_count
            occurrence_count=$(echo "${count_line}" | awk '{print $1}')
            local message
            message=$(echo "${count_line}" | sed 's/^ *[0-9]* *//' | cut -d'|' -f2-)

            # Truncate very long messages
            local display_message="${message}"
            if [ ${#display_message} -gt 200 ]; then
                display_message="${display_message:0:200}..."
            fi

            echo "### ${issue_num}. \`${display_message}\`" >> "${output}"
            echo "" >> "${output}"

            # Find which versions this issue appears in and count per version
            local ver_counts=""
            for ver in "${VERSIONS[@]}"; do
                local ver_count
                ver_count=$(grep "^${severity}|${ver}|" "${all_issues}" | \
                    awk -F'|' '{print $3}' | \
                    grep -cF "${message}" 2>/dev/null || echo "0")
                if [ "${ver_count}" -gt 0 ]; then
                    if [ -n "${ver_counts}" ]; then
                        ver_counts="${ver_counts}, "
                    fi
                    ver_counts="${ver_counts}PHP ${ver}: ${ver_count}"
                fi
            done

            echo "- **Total occurrences**: ${occurrence_count} (${ver_counts})" >> "${output}"

            # Find example file locations from original messages
            local example_files="${tmp_dir}/example_files_${severity}_${issue_num}.txt"
            grep "|${message}" "${all_issues}" | \
                awk -F'|' '{print $4}' | \
                grep -oE "(/[^ ]*\.(php|inc))(:[0-9]+| on line [0-9]+)" | \
                sed 's|/app/workspace/||g' | \
                sed 's|/app/source/||g' | \
                sort -u | head -5 > "${example_files}" 2>/dev/null || true

            if [ -s "${example_files}" ]; then
                echo "- **Example locations**:" >> "${output}"
                while IFS= read -r loc; do
                    echo "  - \`${loc}\`" >> "${output}"
                done < "${example_files}"
            fi

            # Find matching fix suggestion
            local suggestion_found=false
            for rule in "${FIX_RULES[@]}"; do
                local pattern
                pattern=$(echo "${rule}" | cut -d'|' -f1)
                local rule_severity
                rule_severity=$(echo "${rule}" | cut -d'|' -f2)
                local suggestion
                suggestion=$(echo "${rule}" | cut -d'|' -f3-)

                if echo "${message}" | grep -qiE "${pattern}" 2>/dev/null; then
                    echo "- **Suggested fix**: ${suggestion}" >> "${output}"
                    suggestion_found=true
                    break
                fi
            done

            if [ "${suggestion_found}" = false ]; then
                echo "- **Suggested fix**: Review the PHP ${VERSIONS[*]} migration guides for this ${severity}. Check [php.net/manual/en/migration81.php](https://www.php.net/manual/en/migration81.php) and subsequent versions." >> "${output}"
            fi

            echo "" >> "${output}"
        done < "${severity_issues}"
    done

    # If no issues found at all
    if [ "${total_unique}" -eq 0 ]; then
        cat >> "${output}" <<EOF
## No Issues Found

No PHP errors, warnings, deprecations, or notices were detected across all tested versions.

EOF
    fi

    echo "---" >> "${output}"
    echo "*Generated by [PHP SDK Regression Test Suite](regression/README.md)*" >> "${output}"

    # Cleanup temp files
    rm -rf "${tmp_dir}"
}

# =============================================================================
# REPORT 3: Coverage Report
# =============================================================================
generate_coverage_report() {
    local output="${REPORTS_DIR}/coverage-report.md"
    echo "  Generating coverage report ..."

    # Find the best coverage file (prefer highest PHP version that has coverage data)
    local coverage_file=""
    local coverage_version=""
    for ver in $(echo "${VERSIONS[*]}" | tr ' ' '\n' | sort -rV); do
        local candidate="${REPORTS_DIR}/php-${ver}/coverage-clover.xml"
        if [ -f "${candidate}" ] && [ -s "${candidate}" ]; then
            coverage_file="${candidate}"
            coverage_version="${ver}"
            break
        fi
    done

    if [ -z "${coverage_file}" ]; then
        cat > "${output}" <<EOF
# Code Coverage Report

> Auto-generated by the PHP SDK regression test suite.
> Report date: ${REPORT_DATE}

## No Coverage Data Available

No coverage data was collected. This may be because:
- All tests failed before coverage could be collected
- The PCOV extension was not available in the test containers
- Coverage collection was disabled

To enable coverage, ensure PCOV is installed and run:
\`\`\`bash
bash regression/run.sh
\`\`\`

---
*Generated by [PHP SDK Regression Test Suite](regression/README.md)*
EOF
        return
    fi

    echo "  Using coverage data from PHP ${coverage_version}"

    # Parse clover XML to extract per-file coverage
    # Clover XML format:
    #   <file name="/path/to/file.php">
    #     <metrics ... statements="100" coveredstatements="80" ... />
    #   </file>

    local tmp_dir="${REPORTS_DIR}/.tmp_coverage"
    rm -rf "${tmp_dir}"
    mkdir -p "${tmp_dir}"

    local coverage_data="${tmp_dir}/coverage_data.txt"
    > "${coverage_data}"

    # Extract file-level metrics from clover XML using awk
    awk '
    /<file name=/ {
        # Extract file path
        match($0, /name="([^"]*)"/, arr)
        current_file = arr[1]
        # Remove workspace prefix
        gsub(/\/app\/workspace\//, "", current_file)
        gsub(/\/app\/source\//, "", current_file)
    }
    /<metrics / && current_file != "" {
        statements = 0
        covered = 0
        # Extract statements count
        if (match($0, /statements="([0-9]+)"/, arr)) {
            statements = arr[1]
        }
        # Extract covered statements count
        if (match($0, /coveredstatements="([0-9]+)"/, arr)) {
            covered = arr[1]
        }
        if (statements > 0) {
            pct = (covered / statements) * 100
            printf "%s|%d|%d|%.1f\n", current_file, statements, covered, pct
        }
        current_file = ""
    }
    ' "${coverage_file}" > "${coverage_data}"

    # Calculate overall coverage
    local total_statements=0
    local total_covered=0

    while IFS='|' read -r file stmts cov pct; do
        total_statements=$((total_statements + stmts))
        total_covered=$((total_covered + cov))
    done < "${coverage_data}"

    local overall_pct="0.0"
    if [ "${total_statements}" -gt 0 ]; then
        overall_pct=$(awk "BEGIN {printf \"%.1f\", (${total_covered}/${total_statements})*100}")
    fi

    # Sort by coverage percentage (high to low)
    local sorted_data="${tmp_dir}/sorted_data.txt"
    sort -t'|' -k4 -rn "${coverage_data}" > "${sorted_data}"

    # Count files below threshold
    local low_coverage_count=0
    local total_files=0
    while IFS='|' read -r file stmts cov pct; do
        total_files=$((total_files + 1))
        local pct_int
        pct_int=$(echo "${pct}" | cut -d'.' -f1)
        if [ "${pct_int}" -lt 60 ]; then
            low_coverage_count=$((low_coverage_count + 1))
        fi
    done < "${sorted_data}"

    # Write report
    cat > "${output}" <<EOF
# Code Coverage Report

> Auto-generated by the PHP SDK regression test suite.
> Report date: ${REPORT_DATE}
> Coverage data from: PHP ${coverage_version}

## Overall Coverage

| Metric | Value |
|--------|-------|
| **Overall line coverage** | **${overall_pct}%** |
| Total statements | ${total_statements} |
| Covered statements | ${total_covered} |
| Total files | ${total_files} |
| Files below 60% coverage | ${low_coverage_count} |

EOF

    # Overall status indicator
    local overall_int
    overall_int=$(echo "${overall_pct}" | cut -d'.' -f1)
    if [ "${overall_int}" -ge 80 ]; then
        echo "> ✅ Overall coverage is **good** (>= 80%)" >> "${output}"
    elif [ "${overall_int}" -ge 60 ]; then
        echo "> ⚠️ Overall coverage is **moderate** (>= 60%, < 80%)" >> "${output}"
    else
        echo "> ❌ Overall coverage is **low** (< 60%)" >> "${output}"
    fi

    echo "" >> "${output}"
    echo "## Per-File Coverage" >> "${output}"
    echo "" >> "${output}"
    echo "> Files are sorted by coverage percentage (high to low)." >> "${output}"
    echo "> Files with coverage below 60% are marked with ⚠️ **LOW**." >> "${output}"
    echo "" >> "${output}"

    echo "| # | File | Statements | Covered | Coverage | Status |" >> "${output}"
    echo "|--:|------|:----------:|:-------:|:--------:|:------:|" >> "${output}"

    local file_num=0
    while IFS='|' read -r file stmts cov pct; do
        file_num=$((file_num + 1))
        local pct_int
        pct_int=$(echo "${pct}" | cut -d'.' -f1)
        local status_icon="✅"

        if [ "${pct_int}" -lt 60 ]; then
            status_icon="⚠️ **LOW**"
        elif [ "${pct_int}" -lt 80 ]; then
            status_icon="🔸"
        fi

        # Shorten file path for display (keep relative to src/)
        local display_file="${file}"

        echo "| ${file_num} | \`${display_file}\` | ${stmts} | ${cov} | ${pct}% | ${status_icon} |" >> "${output}"
    done < "${sorted_data}"

    # Low coverage details section
    if [ "${low_coverage_count}" -gt 0 ]; then
        echo "" >> "${output}"
        echo "## Files Requiring Attention (< 60% Coverage)" >> "${output}"
        echo "" >> "${output}"
        echo "The following ${low_coverage_count} file(s) have coverage below the 60% threshold and should be prioritized for additional test coverage:" >> "${output}"
        echo "" >> "${output}"

        local low_num=0
        while IFS='|' read -r file stmts cov pct; do
            local pct_int
            pct_int=$(echo "${pct}" | cut -d'.' -f1)
            if [ "${pct_int}" -lt 60 ]; then
                low_num=$((low_num + 1))
                local uncovered=$((stmts - cov))
                echo "${low_num}. ⚠️ \`${file}\` — **${pct}%** coverage (${uncovered} uncovered statements out of ${stmts})" >> "${output}"
            fi
        done < "${sorted_data}"
    fi

    echo "" >> "${output}"

    # Cross-version coverage comparison (if multiple versions have coverage data)
    local versions_with_coverage=()
    for ver in "${VERSIONS[@]}"; do
        if [ -f "${REPORTS_DIR}/php-${ver}/coverage-clover.xml" ] && [ -s "${REPORTS_DIR}/php-${ver}/coverage-clover.xml" ]; then
            versions_with_coverage+=("${ver}")
        fi
    done

    if [ ${#versions_with_coverage[@]} -gt 1 ]; then
        echo "## Cross-Version Coverage Comparison" >> "${output}"
        echo "" >> "${output}"
        echo "| PHP Version | Overall Coverage |" >> "${output}"
        echo "|:-----------:|:----------------:|" >> "${output}"

        for ver in "${versions_with_coverage[@]}"; do
            local ver_file="${REPORTS_DIR}/php-${ver}/coverage-clover.xml"
            local ver_stmts=0
            local ver_cov=0

            # Quick parse for totals
            local project_metrics
            project_metrics=$(grep '<metrics' "${ver_file}" | tail -1)
            if [ -n "${project_metrics}" ]; then
                ver_stmts=$(echo "${project_metrics}" | grep -oE 'statements="[0-9]+"' | grep -oE '[0-9]+')
                ver_cov=$(echo "${project_metrics}" | grep -oE 'coveredstatements="[0-9]+"' | grep -oE '[0-9]+')
            fi

            local ver_pct="0.0"
            if [ -n "${ver_stmts}" ] && [ "${ver_stmts}" -gt 0 ]; then
                ver_pct=$(awk "BEGIN {printf \"%.1f\", (${ver_cov}/${ver_stmts})*100}")
            fi

            echo "| ${ver} | ${ver_pct}% |" >> "${output}"
        done

        echo "" >> "${output}"
    fi

    echo "---" >> "${output}"
    echo "*Generated by [PHP SDK Regression Test Suite](regression/README.md)*" >> "${output}"

    # Cleanup
    rm -rf "${tmp_dir}"
}

# =============================================================================
# Main
# =============================================================================

echo ""
echo "=========================================="
echo "  Generating Regression Test Reports"
echo "=========================================="
echo ""

generate_compatibility_report
generate_developer_fix_report
generate_coverage_report

echo ""
echo "=========================================="
echo "  Reports generated successfully"
echo "=========================================="
echo ""
echo "  📄 ${REPORTS_DIR}/compatibility-report.md"
echo "  📄 ${REPORTS_DIR}/developer-fix-report.md"
echo "  📄 ${REPORTS_DIR}/coverage-report.md"
echo ""
