<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table_store.proto

namespace Aliyun\OTS\ProtoBuffer\Protocol;

/**
 * Protobuf enum <code>Aliyun\OTS\ProtoBuffer\Protocol\ActionType</code>
 */
class ActionType
{
    /**
     * Generated from protobuf enum <code>PUT_ROW = 1;</code>
     */
    const PUT_ROW = 1;
    /**
     * Generated from protobuf enum <code>UPDATE_ROW = 2;</code>
     */
    const UPDATE_ROW = 2;
    /**
     * Generated from protobuf enum <code>DELETE_ROW = 3;</code>
     */
    const DELETE_ROW = 3;
}

