<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table_store_search.proto

namespace Aliyun\OTS\ProtoBuffer\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>aliyun.OTS.ProtoBuffer.Protocol.Aggregations</code>
 */
class Aggregations extends \Aliyun\OTS\ProtoBuffer\Protocol\Message
{
    /**
     * Generated from protobuf field <code>repeated .aliyun.OTS.ProtoBuffer.Protocol.Aggregation aggs = 1;</code>
     */
    private $aggs;
    private $has_aggs = false;

    public function __construct() {
        \GPBMetadata\TableStoreSearch::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>repeated .aliyun.OTS.ProtoBuffer.Protocol.Aggregation aggs = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAggs()
    {
        return $this->aggs;
    }

    /**
     * Generated from protobuf field <code>repeated .aliyun.OTS.ProtoBuffer.Protocol.Aggregation aggs = 1;</code>
     * @param \Aliyun\OTS\ProtoBuffer\Protocol\Aggregation[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAggs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Aliyun\OTS\ProtoBuffer\Protocol\Aggregation::class);
        $this->aggs = $arr;
        $this->has_aggs = true;

        return $this;
    }

    public function hasAggs()
    {
        return $this->has_aggs;
    }

}

