<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table_store_search.proto

namespace Aliyun\OTS\ProtoBuffer\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>aliyun.OTS.ProtoBuffer.Protocol.AggregationResult</code>
 */
class AggregationResult extends \Aliyun\OTS\ProtoBuffer\Protocol\Message
{
    /**
     * Generated from protobuf field <code>optional string name = 1;</code>
     */
    private $name = '';
    private $has_name = false;
    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.AggregationType type = 2;</code>
     */
    private $type = 0;
    private $has_type = false;
    /**
     * encoded by XxxAggregationResult
     *
     * Generated from protobuf field <code>optional bytes agg_result = 3;</code>
     */
    private $agg_result = '';
    private $has_agg_result = false;

    public function __construct() {
        \GPBMetadata\TableStoreSearch::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>optional string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>optional string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;
        $this->has_name = true;

        return $this;
    }

    public function hasName()
    {
        return $this->has_name;
    }

    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.AggregationType type = 2;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.AggregationType type = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Aliyun\OTS\ProtoBuffer\Protocol\AggregationType::class);
        $this->type = $var;
        $this->has_type = true;

        return $this;
    }

    public function hasType()
    {
        return $this->has_type;
    }

    /**
     * encoded by XxxAggregationResult
     *
     * Generated from protobuf field <code>optional bytes agg_result = 3;</code>
     * @return string
     */
    public function getAggResult()
    {
        return $this->agg_result;
    }

    /**
     * encoded by XxxAggregationResult
     *
     * Generated from protobuf field <code>optional bytes agg_result = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setAggResult($var)
    {
        GPBUtil::checkString($var, False);
        $this->agg_result = $var;
        $this->has_agg_result = true;

        return $this;
    }

    public function hasAggResult()
    {
        return $this->has_agg_result;
    }

}

