<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table_store_search.proto

namespace Aliyun\OTS\ProtoBuffer\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>aliyun.OTS.ProtoBuffer.Protocol.AggregationsResult</code>
 */
class AggregationsResult extends \Aliyun\OTS\ProtoBuffer\Protocol\Message
{
    /**
     * Generated from protobuf field <code>repeated .aliyun.OTS.ProtoBuffer.Protocol.AggregationResult agg_results = 1;</code>
     */
    private $agg_results;
    private $has_agg_results = false;

    public function __construct() {
        \GPBMetadata\TableStoreSearch::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>repeated .aliyun.OTS.ProtoBuffer.Protocol.AggregationResult agg_results = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAggResults()
    {
        return $this->agg_results;
    }

    /**
     * Generated from protobuf field <code>repeated .aliyun.OTS.ProtoBuffer.Protocol.AggregationResult agg_results = 1;</code>
     * @param \Aliyun\OTS\ProtoBuffer\Protocol\AggregationResult[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAggResults($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Aliyun\OTS\ProtoBuffer\Protocol\AggregationResult::class);
        $this->agg_results = $arr;
        $this->has_agg_results = true;

        return $this;
    }

    public function hasAggResults()
    {
        return $this->has_agg_results;
    }

}

