<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table_store_search.proto

namespace Aliyun\OTS\ProtoBuffer\Protocol;

/**
 * Protobuf enum <code>Aliyun\OTS\ProtoBuffer\Protocol\AggregationType</code>
 */
class AggregationType
{
    /**
     * Generated from protobuf enum <code>AGG_AVG = 1;</code>
     */
    const AGG_AVG = 1;
    /**
     * Generated from protobuf enum <code>AGG_MAX = 2;</code>
     */
    const AGG_MAX = 2;
    /**
     * Generated from protobuf enum <code>AGG_MIN = 3;</code>
     */
    const AGG_MIN = 3;
    /**
     * Generated from protobuf enum <code>AGG_SUM = 4;</code>
     */
    const AGG_SUM = 4;
    /**
     * Generated from protobuf enum <code>AGG_COUNT = 5;</code>
     */
    const AGG_COUNT = 5;
    /**
     * Generated from protobuf enum <code>AGG_DISTINCT_COUNT = 6;</code>
     */
    const AGG_DISTINCT_COUNT = 6;
    /**
     * Generated from protobuf enum <code>AGG_TOP_ROWS = 7;</code>
     */
    const AGG_TOP_ROWS = 7;
    /**
     * Generated from protobuf enum <code>AGG_PERCENTILES = 8;</code>
     */
    const AGG_PERCENTILES = 8;
}

