<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table_store.proto

namespace Aliyun\OTS\ProtoBuffer\Protocol;

/**
 * Protobuf enum <code>Aliyun\OTS\ProtoBuffer\Protocol\BloomFilterType</code>
 */
class BloomFilterType
{
    /**
     * Generated from protobuf enum <code>NONE = 1;</code>
     */
    const NONE = 1;
    /**
     * Generated from protobuf enum <code>CELL = 2;</code>
     */
    const CELL = 2;
    /**
     * Generated from protobuf enum <code>ROW = 3;</code>
     */
    const ROW = 3;
}

