<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table_store.proto

namespace Aliyun\OTS\ProtoBuffer\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>aliyun.OTS.ProtoBuffer.Protocol.CapacityUnit</code>
 */
class CapacityUnit extends \Aliyun\OTS\ProtoBuffer\Protocol\Message
{
    /**
     * Generated from protobuf field <code>optional int32 read = 1;</code>
     */
    private $read = 0;
    private $has_read = false;
    /**
     * Generated from protobuf field <code>optional int32 write = 2;</code>
     */
    private $write = 0;
    private $has_write = false;

    public function __construct() {
        \GPBMetadata\TableStore::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>optional int32 read = 1;</code>
     * @return int
     */
    public function getRead()
    {
        return $this->read;
    }

    /**
     * Generated from protobuf field <code>optional int32 read = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setRead($var)
    {
        GPBUtil::checkInt32($var);
        $this->read = $var;
        $this->has_read = true;

        return $this;
    }

    public function hasRead()
    {
        return $this->has_read;
    }

    /**
     * Generated from protobuf field <code>optional int32 write = 2;</code>
     * @return int
     */
    public function getWrite()
    {
        return $this->write;
    }

    /**
     * Generated from protobuf field <code>optional int32 write = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setWrite($var)
    {
        GPBUtil::checkInt32($var);
        $this->write = $var;
        $this->has_write = true;

        return $this;
    }

    public function hasWrite()
    {
        return $this->has_write;
    }

}

