<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table_store_search.proto

namespace Aliyun\OTS\ProtoBuffer\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>aliyun.OTS.ProtoBuffer.Protocol.ColumnsToGet</code>
 */
class ColumnsToGet extends \Aliyun\OTS\ProtoBuffer\Protocol\Message
{
    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.ColumnReturnType return_type = 1;</code>
     */
    private $return_type = 0;
    private $has_return_type = false;
    /**
     * Generated from protobuf field <code>repeated string column_names = 2;</code>
     */
    private $column_names;
    private $has_column_names = false;

    public function __construct() {
        \GPBMetadata\TableStoreSearch::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.ColumnReturnType return_type = 1;</code>
     * @return int
     */
    public function getReturnType()
    {
        return $this->return_type;
    }

    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.ColumnReturnType return_type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setReturnType($var)
    {
        GPBUtil::checkEnum($var, \Aliyun\OTS\ProtoBuffer\Protocol\ColumnReturnType::class);
        $this->return_type = $var;
        $this->has_return_type = true;

        return $this;
    }

    public function hasReturnType()
    {
        return $this->has_return_type;
    }

    /**
     * Generated from protobuf field <code>repeated string column_names = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getColumnNames()
    {
        return $this->column_names;
    }

    /**
     * Generated from protobuf field <code>repeated string column_names = 2;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setColumnNames($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->column_names = $arr;
        $this->has_column_names = true;

        return $this;
    }

    public function hasColumnNames()
    {
        return $this->has_column_names;
    }

}

