<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table_store_search.proto

namespace Aliyun\OTS\ProtoBuffer\Protocol;

/**
 * Protobuf enum <code>Aliyun\OTS\ProtoBuffer\Protocol\ColumnReturnType</code>
 */
class ColumnReturnType
{
    /**
     * Generated from protobuf enum <code>RETURN_ALL = 1;</code>
     */
    const RETURN_ALL = 1;
    /**
     * Generated from protobuf enum <code>RETURN_SPECIFIED = 2;</code>
     */
    const RETURN_SPECIFIED = 2;
    /**
     * Generated from protobuf enum <code>RETURN_NONE = 3;</code>
     */
    const RETURN_NONE = 3;
    /**
     * Generated from protobuf enum <code>RETURN_ALL_FROM_INDEX = 4;</code>
     */
    const RETURN_ALL_FROM_INDEX = 4;
}

