<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table_store.proto

namespace Aliyun\OTS\ProtoBuffer\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 **
 * Locations where splits lies in.
 * By the managed nature of TableStore, these locations are no more than hints.
 * If a location is not suitable to be seen, an empty string will be placed.
 *
 * Generated from protobuf message <code>aliyun.OTS.ProtoBuffer.Protocol.ComputeSplitPointsBySizeResponse.SplitLocation</code>
 */
class ComputeSplitPointsBySizeResponse_SplitLocation extends \Aliyun\OTS\ProtoBuffer\Protocol\Message
{
    /**
     * Generated from protobuf field <code>required string location = 1;</code>
     */
    private $location = '';
    private $has_location = false;
    /**
     * Generated from protobuf field <code>required sint64 repeat = 2;</code>
     */
    private $repeat = 0;
    private $has_repeat = false;

    public function __construct() {
        \GPBMetadata\TableStore::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>required string location = 1;</code>
     * @return string
     */
    public function getLocation()
    {
        return $this->location;
    }

    /**
     * Generated from protobuf field <code>required string location = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setLocation($var)
    {
        GPBUtil::checkString($var, True);
        $this->location = $var;
        $this->has_location = true;

        return $this;
    }

    public function hasLocation()
    {
        return $this->has_location;
    }

    /**
     * Generated from protobuf field <code>required sint64 repeat = 2;</code>
     * @return int|string
     */
    public function getRepeat()
    {
        return $this->repeat;
    }

    /**
     * Generated from protobuf field <code>required sint64 repeat = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRepeat($var)
    {
        GPBUtil::checkInt64($var);
        $this->repeat = $var;
        $this->has_repeat = true;

        return $this;
    }

    public function hasRepeat()
    {
        return $this->has_repeat;
    }

}

