<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table_store_filter.proto

namespace Aliyun\OTS\ProtoBuffer\Protocol;

/**
 * Protobuf enum <code>Aliyun\OTS\ProtoBuffer\Protocol\ComparatorType</code>
 */
class ComparatorType
{
    /**
     * Generated from protobuf enum <code>CT_EQUAL = 1;</code>
     */
    const CT_EQUAL = 1;
    /**
     * Generated from protobuf enum <code>CT_NOT_EQUAL = 2;</code>
     */
    const CT_NOT_EQUAL = 2;
    /**
     * Generated from protobuf enum <code>CT_GREATER_THAN = 3;</code>
     */
    const CT_GREATER_THAN = 3;
    /**
     * Generated from protobuf enum <code>CT_GREATER_EQUAL = 4;</code>
     */
    const CT_GREATER_EQUAL = 4;
    /**
     * Generated from protobuf enum <code>CT_LESS_THAN = 5;</code>
     */
    const CT_LESS_THAN = 5;
    /**
     * Generated from protobuf enum <code>CT_LESS_EQUAL = 6;</code>
     */
    const CT_LESS_EQUAL = 6;
}

