<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table_store_search.proto

namespace Aliyun\OTS\ProtoBuffer\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>aliyun.OTS.ProtoBuffer.Protocol.CreateSearchIndexRequest</code>
 */
class CreateSearchIndexRequest extends \Aliyun\OTS\ProtoBuffer\Protocol\Message
{
    /**
     * Generated from protobuf field <code>required string table_name = 1;</code>
     */
    private $table_name = '';
    private $has_table_name = false;
    /**
     * Generated from protobuf field <code>required string index_name = 2;</code>
     */
    private $index_name = '';
    private $has_index_name = false;
    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.IndexSchema schema = 3;</code>
     */
    private $schema = null;
    private $has_schema = false;
    /**
     * Generated from protobuf field <code>optional string source_index_name = 4;</code>
     */
    private $source_index_name = '';
    private $has_source_index_name = false;
    /**
     * unit is seconds
     *
     * Generated from protobuf field <code>optional int32 time_to_live = 5;</code>
     */
    private $time_to_live = 0;
    private $has_time_to_live = false;

    public function __construct() {
        \GPBMetadata\TableStoreSearch::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>required string table_name = 1;</code>
     * @return string
     */
    public function getTableName()
    {
        return $this->table_name;
    }

    /**
     * Generated from protobuf field <code>required string table_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTableName($var)
    {
        GPBUtil::checkString($var, True);
        $this->table_name = $var;
        $this->has_table_name = true;

        return $this;
    }

    public function hasTableName()
    {
        return $this->has_table_name;
    }

    /**
     * Generated from protobuf field <code>required string index_name = 2;</code>
     * @return string
     */
    public function getIndexName()
    {
        return $this->index_name;
    }

    /**
     * Generated from protobuf field <code>required string index_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setIndexName($var)
    {
        GPBUtil::checkString($var, True);
        $this->index_name = $var;
        $this->has_index_name = true;

        return $this;
    }

    public function hasIndexName()
    {
        return $this->has_index_name;
    }

    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.IndexSchema schema = 3;</code>
     * @return \Aliyun\OTS\ProtoBuffer\Protocol\IndexSchema
     */
    public function getSchema()
    {
        return $this->schema;
    }

    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.IndexSchema schema = 3;</code>
     * @param \Aliyun\OTS\ProtoBuffer\Protocol\IndexSchema $var
     * @return $this
     */
    public function setSchema($var)
    {
        GPBUtil::checkMessage($var, \Aliyun\OTS\ProtoBuffer\Protocol\IndexSchema::class);
        $this->schema = $var;
        $this->has_schema = true;

        return $this;
    }

    public function hasSchema()
    {
        return $this->has_schema;
    }

    /**
     * Generated from protobuf field <code>optional string source_index_name = 4;</code>
     * @return string
     */
    public function getSourceIndexName()
    {
        return $this->source_index_name;
    }

    /**
     * Generated from protobuf field <code>optional string source_index_name = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setSourceIndexName($var)
    {
        GPBUtil::checkString($var, True);
        $this->source_index_name = $var;
        $this->has_source_index_name = true;

        return $this;
    }

    public function hasSourceIndexName()
    {
        return $this->has_source_index_name;
    }

    /**
     * unit is seconds
     *
     * Generated from protobuf field <code>optional int32 time_to_live = 5;</code>
     * @return int
     */
    public function getTimeToLive()
    {
        return $this->time_to_live;
    }

    /**
     * unit is seconds
     *
     * Generated from protobuf field <code>optional int32 time_to_live = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setTimeToLive($var)
    {
        GPBUtil::checkInt32($var);
        $this->time_to_live = $var;
        $this->has_time_to_live = true;

        return $this;
    }

    public function hasTimeToLive()
    {
        return $this->has_time_to_live;
    }

}

