<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table_store.proto

namespace Aliyun\OTS\ProtoBuffer\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>aliyun.OTS.ProtoBuffer.Protocol.CreateIndexRequest</code>
 */
class CreateIndexRequest extends \Aliyun\OTS\ProtoBuffer\Protocol\Message
{
    /**
     * Generated from protobuf field <code>required string main_table_name = 1;</code>
     */
    private $main_table_name = '';
    private $has_main_table_name = false;
    /**
     * Generated from protobuf field <code>required .aliyun.OTS.ProtoBuffer.Protocol.IndexMeta index_meta = 2;</code>
     */
    private $index_meta = null;
    private $has_index_meta = false;
    /**
     * Generated from protobuf field <code>optional bool include_base_data = 3;</code>
     */
    private $include_base_data = false;
    private $has_include_base_data = false;

    public function __construct() {
        \GPBMetadata\TableStore::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>required string main_table_name = 1;</code>
     * @return string
     */
    public function getMainTableName()
    {
        return $this->main_table_name;
    }

    /**
     * Generated from protobuf field <code>required string main_table_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMainTableName($var)
    {
        GPBUtil::checkString($var, True);
        $this->main_table_name = $var;
        $this->has_main_table_name = true;

        return $this;
    }

    public function hasMainTableName()
    {
        return $this->has_main_table_name;
    }

    /**
     * Generated from protobuf field <code>required .aliyun.OTS.ProtoBuffer.Protocol.IndexMeta index_meta = 2;</code>
     * @return \Aliyun\OTS\ProtoBuffer\Protocol\IndexMeta
     */
    public function getIndexMeta()
    {
        return $this->index_meta;
    }

    /**
     * Generated from protobuf field <code>required .aliyun.OTS.ProtoBuffer.Protocol.IndexMeta index_meta = 2;</code>
     * @param \Aliyun\OTS\ProtoBuffer\Protocol\IndexMeta $var
     * @return $this
     */
    public function setIndexMeta($var)
    {
        GPBUtil::checkMessage($var, \Aliyun\OTS\ProtoBuffer\Protocol\IndexMeta::class);
        $this->index_meta = $var;
        $this->has_index_meta = true;

        return $this;
    }

    public function hasIndexMeta()
    {
        return $this->has_index_meta;
    }

    /**
     * Generated from protobuf field <code>optional bool include_base_data = 3;</code>
     * @return bool
     */
    public function getIncludeBaseData()
    {
        return $this->include_base_data;
    }

    /**
     * Generated from protobuf field <code>optional bool include_base_data = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setIncludeBaseData($var)
    {
        GPBUtil::checkBool($var);
        $this->include_base_data = $var;
        $this->has_include_base_data = true;

        return $this;
    }

    public function hasIncludeBaseData()
    {
        return $this->has_include_base_data;
    }

}

