<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table_store.proto

namespace Aliyun\OTS\ProtoBuffer\Protocol;

/**
 * Protobuf enum <code>Aliyun\OTS\ProtoBuffer\Protocol\DataBlockType</code>
 */
class DataBlockType
{
    /**
     * Generated from protobuf enum <code>DBT_PLAIN_BUFFER = 0;</code>
     */
    const DBT_PLAIN_BUFFER = 0;
    /**
     * Generated from protobuf enum <code>DBT_SIMPLE_ROW_MATRIX = 1;</code>
     */
    const DBT_SIMPLE_ROW_MATRIX = 1;
}

