<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table_store_search.proto

namespace Aliyun\OTS\ProtoBuffer\Protocol;

/**
 * Protobuf enum <code>Aliyun\OTS\ProtoBuffer\Protocol\DateTimeUnit</code>
 */
class DateTimeUnit
{
    /**
     * Generated from protobuf enum <code>YEAR = 1;</code>
     */
    const YEAR = 1;
    /**
     * 一个季度
     *
     * Generated from protobuf enum <code>QUARTER_YEAR = 2;</code>
     */
    const QUARTER_YEAR = 2;
    /**
     * Generated from protobuf enum <code>MONTH = 3;</code>
     */
    const MONTH = 3;
    /**
     * Generated from protobuf enum <code>WEEK = 4;</code>
     */
    const WEEK = 4;
    /**
     * Generated from protobuf enum <code>DAY = 5;</code>
     */
    const DAY = 5;
    /**
     * Generated from protobuf enum <code>HOUR = 6;</code>
     */
    const HOUR = 6;
    /**
     * Generated from protobuf enum <code>MINUTE = 7;</code>
     */
    const MINUTE = 7;
    /**
     * Generated from protobuf enum <code>SECOND = 8;</code>
     */
    const SECOND = 8;
    /**
     * Generated from protobuf enum <code>MILLISECOND = 9;</code>
     */
    const MILLISECOND = 9;
}

