<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table_store_search.proto

namespace Aliyun\OTS\ProtoBuffer\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>aliyun.OTS.ProtoBuffer.Protocol.DecayFuncDateParam</code>
 */
class DecayFuncDateParam extends \Aliyun\OTS\ProtoBuffer\Protocol\Message
{
    /**
     * Generated from protobuf field <code>optional int64 origin_long = 1;</code>
     */
    private $origin_long = 0;
    private $has_origin_long = false;
    /**
     * Generated from protobuf field <code>optional string origin_string = 2;</code>
     */
    private $origin_string = '';
    private $has_origin_string = false;
    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.DateTimeValue scale = 3;</code>
     */
    private $scale = null;
    private $has_scale = false;
    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.DateTimeValue offset = 4;</code>
     */
    private $offset = null;
    private $has_offset = false;

    public function __construct() {
        \GPBMetadata\TableStoreSearch::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>optional int64 origin_long = 1;</code>
     * @return int|string
     */
    public function getOriginLong()
    {
        return $this->origin_long;
    }

    /**
     * Generated from protobuf field <code>optional int64 origin_long = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setOriginLong($var)
    {
        GPBUtil::checkInt64($var);
        $this->origin_long = $var;
        $this->has_origin_long = true;

        return $this;
    }

    public function hasOriginLong()
    {
        return $this->has_origin_long;
    }

    /**
     * Generated from protobuf field <code>optional string origin_string = 2;</code>
     * @return string
     */
    public function getOriginString()
    {
        return $this->origin_string;
    }

    /**
     * Generated from protobuf field <code>optional string origin_string = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setOriginString($var)
    {
        GPBUtil::checkString($var, True);
        $this->origin_string = $var;
        $this->has_origin_string = true;

        return $this;
    }

    public function hasOriginString()
    {
        return $this->has_origin_string;
    }

    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.DateTimeValue scale = 3;</code>
     * @return \Aliyun\OTS\ProtoBuffer\Protocol\DateTimeValue
     */
    public function getScale()
    {
        return $this->scale;
    }

    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.DateTimeValue scale = 3;</code>
     * @param \Aliyun\OTS\ProtoBuffer\Protocol\DateTimeValue $var
     * @return $this
     */
    public function setScale($var)
    {
        GPBUtil::checkMessage($var, \Aliyun\OTS\ProtoBuffer\Protocol\DateTimeValue::class);
        $this->scale = $var;
        $this->has_scale = true;

        return $this;
    }

    public function hasScale()
    {
        return $this->has_scale;
    }

    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.DateTimeValue offset = 4;</code>
     * @return \Aliyun\OTS\ProtoBuffer\Protocol\DateTimeValue
     */
    public function getOffset()
    {
        return $this->offset;
    }

    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.DateTimeValue offset = 4;</code>
     * @param \Aliyun\OTS\ProtoBuffer\Protocol\DateTimeValue $var
     * @return $this
     */
    public function setOffset($var)
    {
        GPBUtil::checkMessage($var, \Aliyun\OTS\ProtoBuffer\Protocol\DateTimeValue::class);
        $this->offset = $var;
        $this->has_offset = true;

        return $this;
    }

    public function hasOffset()
    {
        return $this->has_offset;
    }

}

