<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table_store_search.proto

namespace Aliyun\OTS\ProtoBuffer\Protocol;

/**
 * Protobuf enum <code>Aliyun\OTS\ProtoBuffer\Protocol\DecayFuncParamType</code>
 */
class DecayFuncParamType
{
    /**
     * Generated from protobuf enum <code>DF_DATE_PARAM = 1;</code>
     */
    const DF_DATE_PARAM = 1;
    /**
     * Generated from protobuf enum <code>DF_NUMERIC_PARAM = 2;</code>
     */
    const DF_NUMERIC_PARAM = 2;
    /**
     * Generated from protobuf enum <code>DF_GEO_PARAM = 3;</code>
     */
    const DF_GEO_PARAM = 3;
}

