<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table_store_search.proto

namespace Aliyun\OTS\ProtoBuffer\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>aliyun.OTS.ProtoBuffer.Protocol.DecayFunction</code>
 */
class DecayFunction extends \Aliyun\OTS\ProtoBuffer\Protocol\Message
{
    /**
     * Generated from protobuf field <code>optional string field_name = 1;</code>
     */
    private $field_name = '';
    private $has_field_name = false;
    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.DecayMathFunction math_function = 2;</code>
     */
    private $math_function = 0;
    private $has_math_function = false;
    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.DecayFuncParamType param_type = 3;</code>
     */
    private $param_type = 0;
    private $has_param_type = false;
    /**
     * Generated from protobuf field <code>optional bytes param = 4;</code>
     */
    private $param = '';
    private $has_param = false;
    /**
     * Generated from protobuf field <code>optional double decay = 5;</code>
     */
    private $decay = 0.0;
    private $has_decay = false;
    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.MultiValueMode multi_value_mode = 6;</code>
     */
    private $multi_value_mode = 0;
    private $has_multi_value_mode = false;

    public function __construct() {
        \GPBMetadata\TableStoreSearch::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>optional string field_name = 1;</code>
     * @return string
     */
    public function getFieldName()
    {
        return $this->field_name;
    }

    /**
     * Generated from protobuf field <code>optional string field_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setFieldName($var)
    {
        GPBUtil::checkString($var, True);
        $this->field_name = $var;
        $this->has_field_name = true;

        return $this;
    }

    public function hasFieldName()
    {
        return $this->has_field_name;
    }

    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.DecayMathFunction math_function = 2;</code>
     * @return int
     */
    public function getMathFunction()
    {
        return $this->math_function;
    }

    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.DecayMathFunction math_function = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setMathFunction($var)
    {
        GPBUtil::checkEnum($var, \Aliyun\OTS\ProtoBuffer\Protocol\DecayMathFunction::class);
        $this->math_function = $var;
        $this->has_math_function = true;

        return $this;
    }

    public function hasMathFunction()
    {
        return $this->has_math_function;
    }

    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.DecayFuncParamType param_type = 3;</code>
     * @return int
     */
    public function getParamType()
    {
        return $this->param_type;
    }

    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.DecayFuncParamType param_type = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setParamType($var)
    {
        GPBUtil::checkEnum($var, \Aliyun\OTS\ProtoBuffer\Protocol\DecayFuncParamType::class);
        $this->param_type = $var;
        $this->has_param_type = true;

        return $this;
    }

    public function hasParamType()
    {
        return $this->has_param_type;
    }

    /**
     * Generated from protobuf field <code>optional bytes param = 4;</code>
     * @return string
     */
    public function getParam()
    {
        return $this->param;
    }

    /**
     * Generated from protobuf field <code>optional bytes param = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setParam($var)
    {
        GPBUtil::checkString($var, False);
        $this->param = $var;
        $this->has_param = true;

        return $this;
    }

    public function hasParam()
    {
        return $this->has_param;
    }

    /**
     * Generated from protobuf field <code>optional double decay = 5;</code>
     * @return float
     */
    public function getDecay()
    {
        return $this->decay;
    }

    /**
     * Generated from protobuf field <code>optional double decay = 5;</code>
     * @param float $var
     * @return $this
     */
    public function setDecay($var)
    {
        GPBUtil::checkDouble($var);
        $this->decay = $var;
        $this->has_decay = true;

        return $this;
    }

    public function hasDecay()
    {
        return $this->has_decay;
    }

    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.MultiValueMode multi_value_mode = 6;</code>
     * @return int
     */
    public function getMultiValueMode()
    {
        return $this->multi_value_mode;
    }

    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.MultiValueMode multi_value_mode = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setMultiValueMode($var)
    {
        GPBUtil::checkEnum($var, \Aliyun\OTS\ProtoBuffer\Protocol\MultiValueMode::class);
        $this->multi_value_mode = $var;
        $this->has_multi_value_mode = true;

        return $this;
    }

    public function hasMultiValueMode()
    {
        return $this->has_multi_value_mode;
    }

}

