<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: defined_column_ops.proto

namespace Aliyun\OTS\ProtoBuffer\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>aliyun.OTS.ProtoBuffer.Protocol.DeleteDefinedColumnRequest</code>
 */
class DeleteDefinedColumnRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string table_name = 1;</code>
     */
    protected $table_name = '';
    /**
     * Generated from protobuf field <code>repeated string columns = 2;</code>
     */
    private $columns;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $table_name
     *     @type string[] $columns
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\DefinedColumnOps::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string table_name = 1;</code>
     * @return string
     */
    public function getTableName()
    {
        return $this->table_name;
    }

    /**
     * Generated from protobuf field <code>string table_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTableName($var)
    {
        GPBUtil::checkString($var, True);
        $this->table_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string columns = 2;</code>
     * @return RepeatedField<string>
     */
    public function getColumns()
    {
        return $this->columns;
    }

    /**
     * Generated from protobuf field <code>repeated string columns = 2;</code>
     * @param string[] $var
     * @return $this
     */
    public function setColumns($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->columns = $arr;

        return $this;
    }

}

