<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table_store.proto

namespace Aliyun\OTS\ProtoBuffer\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>aliyun.OTS.ProtoBuffer.Protocol.DescribeStreamResponse</code>
 */
class DescribeStreamResponse extends \Aliyun\OTS\ProtoBuffer\Protocol\Message
{
    /**
     * Generated from protobuf field <code>required string stream_id = 1;</code>
     */
    private $stream_id = '';
    private $has_stream_id = false;
    /**
     * Generated from protobuf field <code>required int32 expiration_time = 2;</code>
     */
    private $expiration_time = 0;
    private $has_expiration_time = false;
    /**
     * Generated from protobuf field <code>required string table_name = 3;</code>
     */
    private $table_name = '';
    private $has_table_name = false;
    /**
     * Generated from protobuf field <code>required int64 creation_time = 4;</code>
     */
    private $creation_time = 0;
    private $has_creation_time = false;
    /**
     * Generated from protobuf field <code>required .aliyun.OTS.ProtoBuffer.Protocol.StreamStatus stream_status = 5;</code>
     */
    private $stream_status = 0;
    private $has_stream_status = false;
    /**
     * Generated from protobuf field <code>repeated .aliyun.OTS.ProtoBuffer.Protocol.StreamShard shards = 6;</code>
     */
    private $shards;
    private $has_shards = false;
    /**
     * Generated from protobuf field <code>optional string next_shard_id = 7;</code>
     */
    private $next_shard_id = '';
    private $has_next_shard_id = false;

    public function __construct() {
        \GPBMetadata\TableStore::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>required string stream_id = 1;</code>
     * @return string
     */
    public function getStreamId()
    {
        return $this->stream_id;
    }

    /**
     * Generated from protobuf field <code>required string stream_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setStreamId($var)
    {
        GPBUtil::checkString($var, True);
        $this->stream_id = $var;
        $this->has_stream_id = true;

        return $this;
    }

    public function hasStreamId()
    {
        return $this->has_stream_id;
    }

    /**
     * Generated from protobuf field <code>required int32 expiration_time = 2;</code>
     * @return int
     */
    public function getExpirationTime()
    {
        return $this->expiration_time;
    }

    /**
     * Generated from protobuf field <code>required int32 expiration_time = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setExpirationTime($var)
    {
        GPBUtil::checkInt32($var);
        $this->expiration_time = $var;
        $this->has_expiration_time = true;

        return $this;
    }

    public function hasExpirationTime()
    {
        return $this->has_expiration_time;
    }

    /**
     * Generated from protobuf field <code>required string table_name = 3;</code>
     * @return string
     */
    public function getTableName()
    {
        return $this->table_name;
    }

    /**
     * Generated from protobuf field <code>required string table_name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setTableName($var)
    {
        GPBUtil::checkString($var, True);
        $this->table_name = $var;
        $this->has_table_name = true;

        return $this;
    }

    public function hasTableName()
    {
        return $this->has_table_name;
    }

    /**
     * Generated from protobuf field <code>required int64 creation_time = 4;</code>
     * @return int|string
     */
    public function getCreationTime()
    {
        return $this->creation_time;
    }

    /**
     * Generated from protobuf field <code>required int64 creation_time = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCreationTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->creation_time = $var;
        $this->has_creation_time = true;

        return $this;
    }

    public function hasCreationTime()
    {
        return $this->has_creation_time;
    }

    /**
     * Generated from protobuf field <code>required .aliyun.OTS.ProtoBuffer.Protocol.StreamStatus stream_status = 5;</code>
     * @return int
     */
    public function getStreamStatus()
    {
        return $this->stream_status;
    }

    /**
     * Generated from protobuf field <code>required .aliyun.OTS.ProtoBuffer.Protocol.StreamStatus stream_status = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setStreamStatus($var)
    {
        GPBUtil::checkEnum($var, \Aliyun\OTS\ProtoBuffer\Protocol\StreamStatus::class);
        $this->stream_status = $var;
        $this->has_stream_status = true;

        return $this;
    }

    public function hasStreamStatus()
    {
        return $this->has_stream_status;
    }

    /**
     * Generated from protobuf field <code>repeated .aliyun.OTS.ProtoBuffer.Protocol.StreamShard shards = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getShards()
    {
        return $this->shards;
    }

    /**
     * Generated from protobuf field <code>repeated .aliyun.OTS.ProtoBuffer.Protocol.StreamShard shards = 6;</code>
     * @param \Aliyun\OTS\ProtoBuffer\Protocol\StreamShard[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setShards($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Aliyun\OTS\ProtoBuffer\Protocol\StreamShard::class);
        $this->shards = $arr;
        $this->has_shards = true;

        return $this;
    }

    public function hasShards()
    {
        return $this->has_shards;
    }

    /**
     * Generated from protobuf field <code>optional string next_shard_id = 7;</code>
     * @return string
     */
    public function getNextShardId()
    {
        return $this->next_shard_id;
    }

    /**
     * Generated from protobuf field <code>optional string next_shard_id = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setNextShardId($var)
    {
        GPBUtil::checkString($var, True);
        $this->next_shard_id = $var;
        $this->has_next_shard_id = true;

        return $this;
    }

    public function hasNextShardId()
    {
        return $this->has_next_shard_id;
    }

}

