<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table_store.proto

namespace Aliyun\OTS\ProtoBuffer\Protocol;

/**
 * #############################################  GetRange  ############################################# 
 *
 * Protobuf enum <code>Aliyun\OTS\ProtoBuffer\Protocol\Direction</code>
 */
class Direction
{
    /**
     * Generated from protobuf enum <code>FORWARD = 0;</code>
     */
    const FORWARD = 0;
    /**
     * Generated from protobuf enum <code>BACKWARD = 1;</code>
     */
    const BACKWARD = 1;
}

