<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table_store.proto

namespace Aliyun\OTS\ProtoBuffer\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>aliyun.OTS.ProtoBuffer.Protocol.DropIndexRequest</code>
 */
class DropIndexRequest extends \Aliyun\OTS\ProtoBuffer\Protocol\Message
{
    /**
     * Generated from protobuf field <code>required string main_table_name = 1;</code>
     */
    private $main_table_name = '';
    private $has_main_table_name = false;
    /**
     * Generated from protobuf field <code>required string index_name = 2;</code>
     */
    private $index_name = '';
    private $has_index_name = false;

    public function __construct() {
        \GPBMetadata\TableStore::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>required string main_table_name = 1;</code>
     * @return string
     */
    public function getMainTableName()
    {
        return $this->main_table_name;
    }

    /**
     * Generated from protobuf field <code>required string main_table_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMainTableName($var)
    {
        GPBUtil::checkString($var, True);
        $this->main_table_name = $var;
        $this->has_main_table_name = true;

        return $this;
    }

    public function hasMainTableName()
    {
        return $this->has_main_table_name;
    }

    /**
     * Generated from protobuf field <code>required string index_name = 2;</code>
     * @return string
     */
    public function getIndexName()
    {
        return $this->index_name;
    }

    /**
     * Generated from protobuf field <code>required string index_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setIndexName($var)
    {
        GPBUtil::checkString($var, True);
        $this->index_name = $var;
        $this->has_index_name = true;

        return $this;
    }

    public function hasIndexName()
    {
        return $this->has_index_name;
    }

}

