<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table_store_search.proto

namespace Aliyun\OTS\ProtoBuffer\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * group agg
 *
 * Generated from protobuf message <code>aliyun.OTS.ProtoBuffer.Protocol.FieldRange</code>
 */
class FieldRange extends \Aliyun\OTS\ProtoBuffer\Protocol\Message
{
    /**
     * Generated from protobuf field <code>optional bytes min = 1;</code>
     */
    private $min = '';
    private $has_min = false;
    /**
     * Generated from protobuf field <code>optional bytes max = 2;</code>
     */
    private $max = '';
    private $has_max = false;

    public function __construct() {
        \GPBMetadata\TableStoreSearch::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>optional bytes min = 1;</code>
     * @return string
     */
    public function getMin()
    {
        return $this->min;
    }

    /**
     * Generated from protobuf field <code>optional bytes min = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMin($var)
    {
        GPBUtil::checkString($var, False);
        $this->min = $var;
        $this->has_min = true;

        return $this;
    }

    public function hasMin()
    {
        return $this->has_min;
    }

    /**
     * Generated from protobuf field <code>optional bytes max = 2;</code>
     * @return string
     */
    public function getMax()
    {
        return $this->max;
    }

    /**
     * Generated from protobuf field <code>optional bytes max = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMax($var)
    {
        GPBUtil::checkString($var, False);
        $this->max = $var;
        $this->has_max = true;

        return $this;
    }

    public function hasMax()
    {
        return $this->has_max;
    }

}

