<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table_store_search.proto

namespace Aliyun\OTS\ProtoBuffer\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>aliyun.OTS.ProtoBuffer.Protocol.FieldValueFactorFunction</code>
 */
class FieldValueFactorFunction extends \Aliyun\OTS\ProtoBuffer\Protocol\Message
{
    /**
     * Generated from protobuf field <code>optional string field_name = 1;</code>
     */
    private $field_name = '';
    private $has_field_name = false;
    /**
     * Generated from protobuf field <code>optional float factor = 2;</code>
     */
    private $factor = 0.0;
    private $has_factor = false;
    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.FunctionModifier modifier = 3;</code>
     */
    private $modifier = 0;
    private $has_modifier = false;
    /**
     * Generated from protobuf field <code>optional double missing = 4;</code>
     */
    private $missing = 0.0;
    private $has_missing = false;

    public function __construct() {
        \GPBMetadata\TableStoreSearch::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>optional string field_name = 1;</code>
     * @return string
     */
    public function getFieldName()
    {
        return $this->field_name;
    }

    /**
     * Generated from protobuf field <code>optional string field_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setFieldName($var)
    {
        GPBUtil::checkString($var, True);
        $this->field_name = $var;
        $this->has_field_name = true;

        return $this;
    }

    public function hasFieldName()
    {
        return $this->has_field_name;
    }

    /**
     * Generated from protobuf field <code>optional float factor = 2;</code>
     * @return float
     */
    public function getFactor()
    {
        return $this->factor;
    }

    /**
     * Generated from protobuf field <code>optional float factor = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setFactor($var)
    {
        GPBUtil::checkFloat($var);
        $this->factor = $var;
        $this->has_factor = true;

        return $this;
    }

    public function hasFactor()
    {
        return $this->has_factor;
    }

    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.FunctionModifier modifier = 3;</code>
     * @return int
     */
    public function getModifier()
    {
        return $this->modifier;
    }

    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.FunctionModifier modifier = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setModifier($var)
    {
        GPBUtil::checkEnum($var, \Aliyun\OTS\ProtoBuffer\Protocol\FunctionModifier::class);
        $this->modifier = $var;
        $this->has_modifier = true;

        return $this;
    }

    public function hasModifier()
    {
        return $this->has_modifier;
    }

    /**
     * Generated from protobuf field <code>optional double missing = 4;</code>
     * @return float
     */
    public function getMissing()
    {
        return $this->missing;
    }

    /**
     * Generated from protobuf field <code>optional double missing = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setMissing($var)
    {
        GPBUtil::checkDouble($var);
        $this->missing = $var;
        $this->has_missing = true;

        return $this;
    }

    public function hasMissing()
    {
        return $this->has_missing;
    }

}

