<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table_store_search.proto

namespace Aliyun\OTS\ProtoBuffer\Protocol;

/**
 * Protobuf enum <code>Aliyun\OTS\ProtoBuffer\Protocol\FieldType</code>
 */
class FieldType
{
    /**
     * Generated from protobuf enum <code>LONG = 1;</code>
     */
    const LONG = 1;
    /**
     * Generated from protobuf enum <code>DOUBLE = 2;</code>
     */
    const DOUBLE = 2;
    /**
     * Generated from protobuf enum <code>BOOLEAN = 3;</code>
     */
    const BOOLEAN = 3;
    /**
     * Generated from protobuf enum <code>KEYWORD = 4;</code>
     */
    const KEYWORD = 4;
    /**
     * Generated from protobuf enum <code>TEXT = 5;</code>
     */
    const TEXT = 5;
    /**
     * Generated from protobuf enum <code>NESTED = 6;</code>
     */
    const NESTED = 6;
    /**
     * Generated from protobuf enum <code>GEO_POINT = 7;</code>
     */
    const GEO_POINT = 7;
    /**
     * Generated from protobuf enum <code>DATE = 8;</code>
     */
    const DATE = 8;
}

