<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table_store_search.proto

namespace Aliyun\OTS\ProtoBuffer\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>aliyun.OTS.ProtoBuffer.Protocol.FieldSchema</code>
 */
class FieldSchema extends \Aliyun\OTS\ProtoBuffer\Protocol\Message
{
    /**
     * Generated from protobuf field <code>optional string field_name = 1;</code>
     */
    private $field_name = '';
    private $has_field_name = false;
    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.FieldType field_type = 2;</code>
     */
    private $field_type = 0;
    private $has_field_type = false;
    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.IndexOptions index_options = 3;</code>
     */
    private $index_options = 0;
    private $has_index_options = false;
    /**
     * Generated from protobuf field <code>optional string analyzer = 4;</code>
     */
    private $analyzer = '';
    private $has_analyzer = false;
    /**
     * Generated from protobuf field <code>optional bool index = 5;</code>
     */
    private $index = false;
    private $has_index = false;
    /**
     * Generated from protobuf field <code>optional bool doc_values = 6;</code>
     */
    private $doc_values = false;
    private $has_doc_values = false;
    /**
     * Generated from protobuf field <code>optional bool store = 7;</code>
     */
    private $store = false;
    private $has_store = false;
    /**
     * only for nested type
     *
     * Generated from protobuf field <code>repeated .aliyun.OTS.ProtoBuffer.Protocol.FieldSchema field_schemas = 8;</code>
     */
    private $field_schemas;
    private $has_field_schemas = false;
    /**
     * Generated from protobuf field <code>optional bool is_array = 9;</code>
     */
    private $is_array = false;
    private $has_is_array = false;
    /**
     * Generated from protobuf field <code>optional bytes analyzer_parameter = 10;</code>
     */
    private $analyzer_parameter = '';
    private $has_analyzer_parameter = false;
    /**
     * Generated from protobuf field <code>optional bool is_virtual_field = 11;</code>
     */
    private $is_virtual_field = false;
    private $has_is_virtual_field = false;
    /**
     * Generated from protobuf field <code>repeated string source_field_names = 12;</code>
     */
    private $source_field_names;
    private $has_source_field_names = false;
    /**
     * Generated from protobuf field <code>repeated string date_formats = 13;</code>
     */
    private $date_formats;
    private $has_date_formats = false;

    public function __construct() {
        \GPBMetadata\TableStoreSearch::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>optional string field_name = 1;</code>
     * @return string
     */
    public function getFieldName()
    {
        return $this->field_name;
    }

    /**
     * Generated from protobuf field <code>optional string field_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setFieldName($var)
    {
        GPBUtil::checkString($var, True);
        $this->field_name = $var;
        $this->has_field_name = true;

        return $this;
    }

    public function hasFieldName()
    {
        return $this->has_field_name;
    }

    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.FieldType field_type = 2;</code>
     * @return int
     */
    public function getFieldType()
    {
        return $this->field_type;
    }

    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.FieldType field_type = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setFieldType($var)
    {
        GPBUtil::checkEnum($var, \Aliyun\OTS\ProtoBuffer\Protocol\FieldType::class);
        $this->field_type = $var;
        $this->has_field_type = true;

        return $this;
    }

    public function hasFieldType()
    {
        return $this->has_field_type;
    }

    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.IndexOptions index_options = 3;</code>
     * @return int
     */
    public function getIndexOptions()
    {
        return $this->index_options;
    }

    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.IndexOptions index_options = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setIndexOptions($var)
    {
        GPBUtil::checkEnum($var, \Aliyun\OTS\ProtoBuffer\Protocol\IndexOptions::class);
        $this->index_options = $var;
        $this->has_index_options = true;

        return $this;
    }

    public function hasIndexOptions()
    {
        return $this->has_index_options;
    }

    /**
     * Generated from protobuf field <code>optional string analyzer = 4;</code>
     * @return string
     */
    public function getAnalyzer()
    {
        return $this->analyzer;
    }

    /**
     * Generated from protobuf field <code>optional string analyzer = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setAnalyzer($var)
    {
        GPBUtil::checkString($var, True);
        $this->analyzer = $var;
        $this->has_analyzer = true;

        return $this;
    }

    public function hasAnalyzer()
    {
        return $this->has_analyzer;
    }

    /**
     * Generated from protobuf field <code>optional bool index = 5;</code>
     * @return bool
     */
    public function getIndex()
    {
        return $this->index;
    }

    /**
     * Generated from protobuf field <code>optional bool index = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setIndex($var)
    {
        GPBUtil::checkBool($var);
        $this->index = $var;
        $this->has_index = true;

        return $this;
    }

    public function hasIndex()
    {
        return $this->has_index;
    }

    /**
     * Generated from protobuf field <code>optional bool doc_values = 6;</code>
     * @return bool
     */
    public function getDocValues()
    {
        return $this->doc_values;
    }

    /**
     * Generated from protobuf field <code>optional bool doc_values = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setDocValues($var)
    {
        GPBUtil::checkBool($var);
        $this->doc_values = $var;
        $this->has_doc_values = true;

        return $this;
    }

    public function hasDocValues()
    {
        return $this->has_doc_values;
    }

    /**
     * Generated from protobuf field <code>optional bool store = 7;</code>
     * @return bool
     */
    public function getStore()
    {
        return $this->store;
    }

    /**
     * Generated from protobuf field <code>optional bool store = 7;</code>
     * @param bool $var
     * @return $this
     */
    public function setStore($var)
    {
        GPBUtil::checkBool($var);
        $this->store = $var;
        $this->has_store = true;

        return $this;
    }

    public function hasStore()
    {
        return $this->has_store;
    }

    /**
     * only for nested type
     *
     * Generated from protobuf field <code>repeated .aliyun.OTS.ProtoBuffer.Protocol.FieldSchema field_schemas = 8;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFieldSchemas()
    {
        return $this->field_schemas;
    }

    /**
     * only for nested type
     *
     * Generated from protobuf field <code>repeated .aliyun.OTS.ProtoBuffer.Protocol.FieldSchema field_schemas = 8;</code>
     * @param \Aliyun\OTS\ProtoBuffer\Protocol\FieldSchema[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFieldSchemas($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Aliyun\OTS\ProtoBuffer\Protocol\FieldSchema::class);
        $this->field_schemas = $arr;
        $this->has_field_schemas = true;

        return $this;
    }

    public function hasFieldSchemas()
    {
        return $this->has_field_schemas;
    }

    /**
     * Generated from protobuf field <code>optional bool is_array = 9;</code>
     * @return bool
     */
    public function getIsArray()
    {
        return $this->is_array;
    }

    /**
     * Generated from protobuf field <code>optional bool is_array = 9;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsArray($var)
    {
        GPBUtil::checkBool($var);
        $this->is_array = $var;
        $this->has_is_array = true;

        return $this;
    }

    public function hasIsArray()
    {
        return $this->has_is_array;
    }

    /**
     * Generated from protobuf field <code>optional bytes analyzer_parameter = 10;</code>
     * @return string
     */
    public function getAnalyzerParameter()
    {
        return $this->analyzer_parameter;
    }

    /**
     * Generated from protobuf field <code>optional bytes analyzer_parameter = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setAnalyzerParameter($var)
    {
        GPBUtil::checkString($var, False);
        $this->analyzer_parameter = $var;
        $this->has_analyzer_parameter = true;

        return $this;
    }

    public function hasAnalyzerParameter()
    {
        return $this->has_analyzer_parameter;
    }

    /**
     * Generated from protobuf field <code>optional bool is_virtual_field = 11;</code>
     * @return bool
     */
    public function getIsVirtualField()
    {
        return $this->is_virtual_field;
    }

    /**
     * Generated from protobuf field <code>optional bool is_virtual_field = 11;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsVirtualField($var)
    {
        GPBUtil::checkBool($var);
        $this->is_virtual_field = $var;
        $this->has_is_virtual_field = true;

        return $this;
    }

    public function hasIsVirtualField()
    {
        return $this->has_is_virtual_field;
    }

    /**
     * Generated from protobuf field <code>repeated string source_field_names = 12;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSourceFieldNames()
    {
        return $this->source_field_names;
    }

    /**
     * Generated from protobuf field <code>repeated string source_field_names = 12;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSourceFieldNames($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->source_field_names = $arr;
        $this->has_source_field_names = true;

        return $this;
    }

    public function hasSourceFieldNames()
    {
        return $this->has_source_field_names;
    }

    /**
     * Generated from protobuf field <code>repeated string date_formats = 13;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDateFormats()
    {
        return $this->date_formats;
    }

    /**
     * Generated from protobuf field <code>repeated string date_formats = 13;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDateFormats($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->date_formats = $arr;
        $this->has_date_formats = true;

        return $this;
    }

    public function hasDateFormats()
    {
        return $this->has_date_formats;
    }

}

