<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table_store_search.proto

namespace Aliyun\OTS\ProtoBuffer\Protocol;

/**
 * Protobuf enum <code>Aliyun\OTS\ProtoBuffer\Protocol\FunctionModifier</code>
 */
class FunctionModifier
{
    /**
     * Generated from protobuf enum <code>FM_NONE = 1;</code>
     */
    const FM_NONE = 1;
    /**
     * Generated from protobuf enum <code>FM_LOG = 2;</code>
     */
    const FM_LOG = 2;
    /**
     * Generated from protobuf enum <code>FM_LOG1P = 3;</code>
     */
    const FM_LOG1P = 3;
    /**
     * Generated from protobuf enum <code>FM_LOG2P = 4;</code>
     */
    const FM_LOG2P = 4;
    /**
     * Generated from protobuf enum <code>FM_LN = 5;</code>
     */
    const FM_LN = 5;
    /**
     * Generated from protobuf enum <code>FM_LN1P = 6;</code>
     */
    const FM_LN1P = 6;
    /**
     * Generated from protobuf enum <code>FM_LN2P = 7;</code>
     */
    const FM_LN2P = 7;
    /**
     * Generated from protobuf enum <code>FM_SQUARE = 8;</code>
     */
    const FM_SQUARE = 8;
    /**
     * Generated from protobuf enum <code>FM_SQRT = 9;</code>
     */
    const FM_SQRT = 9;
    /**
     * Generated from protobuf enum <code>FM_RECIPROCAL = 10;</code>
     */
    const FM_RECIPROCAL = 10;
}

