<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table_store_search.proto

namespace Aliyun\OTS\ProtoBuffer\Protocol;

/**
 * Protobuf enum <code>Aliyun\OTS\ProtoBuffer\Protocol\FunctionScoreMode</code>
 */
class FunctionScoreMode
{
    /**
     * Generated from protobuf enum <code>FSM_AVG = 1;</code>
     */
    const FSM_AVG = 1;
    /**
     * Generated from protobuf enum <code>FSM_MAX = 2;</code>
     */
    const FSM_MAX = 2;
    /**
     * Generated from protobuf enum <code>FSM_SUM = 3;</code>
     */
    const FSM_SUM = 3;
    /**
     * Generated from protobuf enum <code>FSM_MIN = 4;</code>
     */
    const FSM_MIN = 4;
    /**
     * Generated from protobuf enum <code>FSM_MULTIPLY = 5;</code>
     */
    const FSM_MULTIPLY = 5;
    /**
     * Generated from protobuf enum <code>FSM_FIRST = 6;</code>
     */
    const FSM_FIRST = 6;
}

