<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table_store_search.proto

namespace Aliyun\OTS\ProtoBuffer\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>aliyun.OTS.ProtoBuffer.Protocol.GeoDistanceQuery</code>
 */
class GeoDistanceQuery extends \Aliyun\OTS\ProtoBuffer\Protocol\Message
{
    /**
     * Generated from protobuf field <code>optional string field_name = 1;</code>
     */
    private $field_name = '';
    private $has_field_name = false;
    /**
     * Generated from protobuf field <code>optional string center_point = 2;</code>
     */
    private $center_point = '';
    private $has_center_point = false;
    /**
     * Generated from protobuf field <code>optional double distance = 3;</code>
     */
    private $distance = 0.0;
    private $has_distance = false;

    public function __construct() {
        \GPBMetadata\TableStoreSearch::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>optional string field_name = 1;</code>
     * @return string
     */
    public function getFieldName()
    {
        return $this->field_name;
    }

    /**
     * Generated from protobuf field <code>optional string field_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setFieldName($var)
    {
        GPBUtil::checkString($var, True);
        $this->field_name = $var;
        $this->has_field_name = true;

        return $this;
    }

    public function hasFieldName()
    {
        return $this->has_field_name;
    }

    /**
     * Generated from protobuf field <code>optional string center_point = 2;</code>
     * @return string
     */
    public function getCenterPoint()
    {
        return $this->center_point;
    }

    /**
     * Generated from protobuf field <code>optional string center_point = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCenterPoint($var)
    {
        GPBUtil::checkString($var, True);
        $this->center_point = $var;
        $this->has_center_point = true;

        return $this;
    }

    public function hasCenterPoint()
    {
        return $this->has_center_point;
    }

    /**
     * Generated from protobuf field <code>optional double distance = 3;</code>
     * @return float
     */
    public function getDistance()
    {
        return $this->distance;
    }

    /**
     * Generated from protobuf field <code>optional double distance = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setDistance($var)
    {
        GPBUtil::checkDouble($var);
        $this->distance = $var;
        $this->has_distance = true;

        return $this;
    }

    public function hasDistance()
    {
        return $this->has_distance;
    }

}

