<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table_store_search.proto

namespace Aliyun\OTS\ProtoBuffer\Protocol;

/**
 * Protobuf enum <code>Aliyun\OTS\ProtoBuffer\Protocol\GeoDistanceType</code>
 */
class GeoDistanceType
{
    /**
     * Generated from protobuf enum <code>GEO_DISTANCE_ARC = 0;</code>
     */
    const GEO_DISTANCE_ARC = 0;
    /**
     * Generated from protobuf enum <code>GEO_DISTANCE_PLANE = 1;</code>
     */
    const GEO_DISTANCE_PLANE = 1;
}

