<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table_store_search.proto

namespace Aliyun\OTS\ProtoBuffer\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>aliyun.OTS.ProtoBuffer.Protocol.GeoGrid</code>
 */
class GeoGrid extends \Aliyun\OTS\ProtoBuffer\Protocol\Message
{
    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.GeoPoint top_left = 1;</code>
     */
    private $top_left = null;
    private $has_top_left = false;
    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.GeoPoint bottom_right = 2;</code>
     */
    private $bottom_right = null;
    private $has_bottom_right = false;

    public function __construct() {
        \GPBMetadata\TableStoreSearch::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.GeoPoint top_left = 1;</code>
     * @return \Aliyun\OTS\ProtoBuffer\Protocol\GeoPoint
     */
    public function getTopLeft()
    {
        return $this->top_left;
    }

    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.GeoPoint top_left = 1;</code>
     * @param \Aliyun\OTS\ProtoBuffer\Protocol\GeoPoint $var
     * @return $this
     */
    public function setTopLeft($var)
    {
        GPBUtil::checkMessage($var, \Aliyun\OTS\ProtoBuffer\Protocol\GeoPoint::class);
        $this->top_left = $var;
        $this->has_top_left = true;

        return $this;
    }

    public function hasTopLeft()
    {
        return $this->has_top_left;
    }

    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.GeoPoint bottom_right = 2;</code>
     * @return \Aliyun\OTS\ProtoBuffer\Protocol\GeoPoint
     */
    public function getBottomRight()
    {
        return $this->bottom_right;
    }

    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.GeoPoint bottom_right = 2;</code>
     * @param \Aliyun\OTS\ProtoBuffer\Protocol\GeoPoint $var
     * @return $this
     */
    public function setBottomRight($var)
    {
        GPBUtil::checkMessage($var, \Aliyun\OTS\ProtoBuffer\Protocol\GeoPoint::class);
        $this->bottom_right = $var;
        $this->has_bottom_right = true;

        return $this;
    }

    public function hasBottomRight()
    {
        return $this->has_bottom_right;
    }

}

