<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table_store_search.proto

namespace Aliyun\OTS\ProtoBuffer\Protocol;

/**
 * Protobuf enum <code>Aliyun\OTS\ProtoBuffer\Protocol\GeoHashPrecision</code>
 */
class GeoHashPrecision
{
    /**
     * Generated from protobuf enum <code>GHP_5009KM_4992KM_1 = 1;</code>
     */
    const GHP_5009KM_4992KM_1 = 1;
    /**
     * Generated from protobuf enum <code>GHP_1252KM_624KM_2 = 2;</code>
     */
    const GHP_1252KM_624KM_2 = 2;
    /**
     * Generated from protobuf enum <code>GHP_156KM_156KM_3 = 3;</code>
     */
    const GHP_156KM_156KM_3 = 3;
    /**
     * Generated from protobuf enum <code>GHP_39KM_19KM_4 = 4;</code>
     */
    const GHP_39KM_19KM_4 = 4;
    /**
     * Generated from protobuf enum <code>GHP_4900M_4900M_5 = 5;</code>
     */
    const GHP_4900M_4900M_5 = 5;
    /**
     * Generated from protobuf enum <code>GHP_1200M_609M_6 = 6;</code>
     */
    const GHP_1200M_609M_6 = 6;
    /**
     * Generated from protobuf enum <code>GHP_152M_152M_7 = 7;</code>
     */
    const GHP_152M_152M_7 = 7;
    /**
     * Generated from protobuf enum <code>GHP_38M_19M_8 = 8;</code>
     */
    const GHP_38M_19M_8 = 8;
    /**
     * Generated from protobuf enum <code>GHP_480CM_480CM_9 = 9;</code>
     */
    const GHP_480CM_480CM_9 = 9;
    /**
     * Generated from protobuf enum <code>GHP_120CM_595MM_10 = 10;</code>
     */
    const GHP_120CM_595MM_10 = 10;
    /**
     * Generated from protobuf enum <code>GHP_149MM_149MM_11 = 11;</code>
     */
    const GHP_149MM_149MM_11 = 11;
    /**
     * Generated from protobuf enum <code>GHP_37MM_19MM_12 = 12;</code>
     */
    const GHP_37MM_19MM_12 = 12;
}

