<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table_store_search.proto

namespace Aliyun\OTS\ProtoBuffer\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>aliyun.OTS.ProtoBuffer.Protocol.GeoPoint</code>
 */
class GeoPoint extends \Aliyun\OTS\ProtoBuffer\Protocol\Message
{
    /**
     * Generated from protobuf field <code>optional double lat = 1;</code>
     */
    private $lat = 0.0;
    private $has_lat = false;
    /**
     * Generated from protobuf field <code>optional double lon = 2;</code>
     */
    private $lon = 0.0;
    private $has_lon = false;

    public function __construct() {
        \GPBMetadata\TableStoreSearch::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>optional double lat = 1;</code>
     * @return float
     */
    public function getLat()
    {
        return $this->lat;
    }

    /**
     * Generated from protobuf field <code>optional double lat = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setLat($var)
    {
        GPBUtil::checkDouble($var);
        $this->lat = $var;
        $this->has_lat = true;

        return $this;
    }

    public function hasLat()
    {
        return $this->has_lat;
    }

    /**
     * Generated from protobuf field <code>optional double lon = 2;</code>
     * @return float
     */
    public function getLon()
    {
        return $this->lon;
    }

    /**
     * Generated from protobuf field <code>optional double lon = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setLon($var)
    {
        GPBUtil::checkDouble($var);
        $this->lon = $var;
        $this->has_lon = true;

        return $this;
    }

    public function hasLon()
    {
        return $this->has_lon;
    }

}

