<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table_store.proto

namespace Aliyun\OTS\ProtoBuffer\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 **
 * HBase支持以下参数：
 *     1. TimeRange或指定time
 *     2. Filter（根据列值或列名来过滤）
 * 我们只支持给同版本的选择条件。
 *
 * Generated from protobuf message <code>aliyun.OTS.ProtoBuffer.Protocol.GetRangeRequest</code>
 */
class GetRangeRequest extends \Aliyun\OTS\ProtoBuffer\Protocol\Message
{
    /**
     * Generated from protobuf field <code>required string table_name = 1;</code>
     */
    private $table_name = '';
    private $has_table_name = false;
    /**
     * Generated from protobuf field <code>required .aliyun.OTS.ProtoBuffer.Protocol.Direction direction = 2;</code>
     */
    private $direction = 0;
    private $has_direction = false;
    /**
     * 不指定则读出所有的列
     *
     * Generated from protobuf field <code>repeated string columns_to_get = 3;</code>
     */
    private $columns_to_get;
    private $has_columns_to_get = false;
    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.TimeRange time_range = 4;</code>
     */
    private $time_range = null;
    private $has_time_range = false;
    /**
     * Generated from protobuf field <code>optional int32 max_versions = 5;</code>
     */
    private $max_versions = 0;
    private $has_max_versions = false;
    /**
     * Generated from protobuf field <code>optional int32 limit = 6;</code>
     */
    private $limit = 0;
    private $has_limit = false;
    /**
     * encoded as InplaceRowChangeSet, but only has primary key
     *
     * Generated from protobuf field <code>required bytes inclusive_start_primary_key = 7;</code>
     */
    private $inclusive_start_primary_key = '';
    private $has_inclusive_start_primary_key = false;
    /**
     * encoded as InplaceRowChangeSet, but only has primary key
     *
     * Generated from protobuf field <code>required bytes exclusive_end_primary_key = 8;</code>
     */
    private $exclusive_end_primary_key = '';
    private $has_exclusive_end_primary_key = false;
    /**
     * 本次读出的数据是否进入BlockCache
     *
     * Generated from protobuf field <code>optional bool cache_blocks = 9 [default = true];</code>
     */
    private $cache_blocks = false;
    private $has_cache_blocks = false;
    /**
     * Generated from protobuf field <code>optional bytes filter = 10;</code>
     */
    private $filter = '';
    private $has_filter = false;
    /**
     * Generated from protobuf field <code>optional string start_column = 11;</code>
     */
    private $start_column = '';
    private $has_start_column = false;
    /**
     * Generated from protobuf field <code>optional string end_column = 12;</code>
     */
    private $end_column = '';
    private $has_end_column = false;
    /**
     * Generated from protobuf field <code>optional bytes token = 13;</code>
     */
    private $token = '';
    private $has_token = false;
    /**
     * Generated from protobuf field <code>optional string transaction_id = 14;</code>
     */
    private $transaction_id = '';
    private $has_transaction_id = false;
    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.DataBlockType data_block_type_hint = 15 [default = DBT_PLAIN_BUFFER];</code>
     */
    private $data_block_type_hint = 0;
    private $has_data_block_type_hint = false;
    /**
     * Generated from protobuf field <code>optional bool return_entire_primary_keys = 16 [default = true];</code>
     */
    private $return_entire_primary_keys = false;
    private $has_return_entire_primary_keys = false;
    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.CompressType compress_type_hint = 17 [default = CPT_NONE];</code>
     */
    private $compress_type_hint = 0;
    private $has_compress_type_hint = false;

    public function __construct() {
        \GPBMetadata\TableStore::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>required string table_name = 1;</code>
     * @return string
     */
    public function getTableName()
    {
        return $this->table_name;
    }

    /**
     * Generated from protobuf field <code>required string table_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTableName($var)
    {
        GPBUtil::checkString($var, True);
        $this->table_name = $var;
        $this->has_table_name = true;

        return $this;
    }

    public function hasTableName()
    {
        return $this->has_table_name;
    }

    /**
     * Generated from protobuf field <code>required .aliyun.OTS.ProtoBuffer.Protocol.Direction direction = 2;</code>
     * @return int
     */
    public function getDirection()
    {
        return $this->direction;
    }

    /**
     * Generated from protobuf field <code>required .aliyun.OTS.ProtoBuffer.Protocol.Direction direction = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setDirection($var)
    {
        GPBUtil::checkEnum($var, \Aliyun\OTS\ProtoBuffer\Protocol\Direction::class);
        $this->direction = $var;
        $this->has_direction = true;

        return $this;
    }

    public function hasDirection()
    {
        return $this->has_direction;
    }

    /**
     * 不指定则读出所有的列
     *
     * Generated from protobuf field <code>repeated string columns_to_get = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getColumnsToGet()
    {
        return $this->columns_to_get;
    }

    /**
     * 不指定则读出所有的列
     *
     * Generated from protobuf field <code>repeated string columns_to_get = 3;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setColumnsToGet($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->columns_to_get = $arr;
        $this->has_columns_to_get = true;

        return $this;
    }

    public function hasColumnsToGet()
    {
        return $this->has_columns_to_get;
    }

    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.TimeRange time_range = 4;</code>
     * @return \Aliyun\OTS\ProtoBuffer\Protocol\TimeRange
     */
    public function getTimeRange()
    {
        return $this->time_range;
    }

    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.TimeRange time_range = 4;</code>
     * @param \Aliyun\OTS\ProtoBuffer\Protocol\TimeRange $var
     * @return $this
     */
    public function setTimeRange($var)
    {
        GPBUtil::checkMessage($var, \Aliyun\OTS\ProtoBuffer\Protocol\TimeRange::class);
        $this->time_range = $var;
        $this->has_time_range = true;

        return $this;
    }

    public function hasTimeRange()
    {
        return $this->has_time_range;
    }

    /**
     * Generated from protobuf field <code>optional int32 max_versions = 5;</code>
     * @return int
     */
    public function getMaxVersions()
    {
        return $this->max_versions;
    }

    /**
     * Generated from protobuf field <code>optional int32 max_versions = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setMaxVersions($var)
    {
        GPBUtil::checkInt32($var);
        $this->max_versions = $var;
        $this->has_max_versions = true;

        return $this;
    }

    public function hasMaxVersions()
    {
        return $this->has_max_versions;
    }

    /**
     * Generated from protobuf field <code>optional int32 limit = 6;</code>
     * @return int
     */
    public function getLimit()
    {
        return $this->limit;
    }

    /**
     * Generated from protobuf field <code>optional int32 limit = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setLimit($var)
    {
        GPBUtil::checkInt32($var);
        $this->limit = $var;
        $this->has_limit = true;

        return $this;
    }

    public function hasLimit()
    {
        return $this->has_limit;
    }

    /**
     * encoded as InplaceRowChangeSet, but only has primary key
     *
     * Generated from protobuf field <code>required bytes inclusive_start_primary_key = 7;</code>
     * @return string
     */
    public function getInclusiveStartPrimaryKey()
    {
        return $this->inclusive_start_primary_key;
    }

    /**
     * encoded as InplaceRowChangeSet, but only has primary key
     *
     * Generated from protobuf field <code>required bytes inclusive_start_primary_key = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setInclusiveStartPrimaryKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->inclusive_start_primary_key = $var;
        $this->has_inclusive_start_primary_key = true;

        return $this;
    }

    public function hasInclusiveStartPrimaryKey()
    {
        return $this->has_inclusive_start_primary_key;
    }

    /**
     * encoded as InplaceRowChangeSet, but only has primary key
     *
     * Generated from protobuf field <code>required bytes exclusive_end_primary_key = 8;</code>
     * @return string
     */
    public function getExclusiveEndPrimaryKey()
    {
        return $this->exclusive_end_primary_key;
    }

    /**
     * encoded as InplaceRowChangeSet, but only has primary key
     *
     * Generated from protobuf field <code>required bytes exclusive_end_primary_key = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setExclusiveEndPrimaryKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->exclusive_end_primary_key = $var;
        $this->has_exclusive_end_primary_key = true;

        return $this;
    }

    public function hasExclusiveEndPrimaryKey()
    {
        return $this->has_exclusive_end_primary_key;
    }

    /**
     * 本次读出的数据是否进入BlockCache
     *
     * Generated from protobuf field <code>optional bool cache_blocks = 9 [default = true];</code>
     * @return bool
     */
    public function getCacheBlocks()
    {
        return $this->cache_blocks;
    }

    /**
     * 本次读出的数据是否进入BlockCache
     *
     * Generated from protobuf field <code>optional bool cache_blocks = 9 [default = true];</code>
     * @param bool $var
     * @return $this
     */
    public function setCacheBlocks($var)
    {
        GPBUtil::checkBool($var);
        $this->cache_blocks = $var;
        $this->has_cache_blocks = true;

        return $this;
    }

    public function hasCacheBlocks()
    {
        return $this->has_cache_blocks;
    }

    /**
     * Generated from protobuf field <code>optional bytes filter = 10;</code>
     * @return string
     */
    public function getFilter()
    {
        return $this->filter;
    }

    /**
     * Generated from protobuf field <code>optional bytes filter = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setFilter($var)
    {
        GPBUtil::checkString($var, False);
        $this->filter = $var;
        $this->has_filter = true;

        return $this;
    }

    public function hasFilter()
    {
        return $this->has_filter;
    }

    /**
     * Generated from protobuf field <code>optional string start_column = 11;</code>
     * @return string
     */
    public function getStartColumn()
    {
        return $this->start_column;
    }

    /**
     * Generated from protobuf field <code>optional string start_column = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setStartColumn($var)
    {
        GPBUtil::checkString($var, True);
        $this->start_column = $var;
        $this->has_start_column = true;

        return $this;
    }

    public function hasStartColumn()
    {
        return $this->has_start_column;
    }

    /**
     * Generated from protobuf field <code>optional string end_column = 12;</code>
     * @return string
     */
    public function getEndColumn()
    {
        return $this->end_column;
    }

    /**
     * Generated from protobuf field <code>optional string end_column = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setEndColumn($var)
    {
        GPBUtil::checkString($var, True);
        $this->end_column = $var;
        $this->has_end_column = true;

        return $this;
    }

    public function hasEndColumn()
    {
        return $this->has_end_column;
    }

    /**
     * Generated from protobuf field <code>optional bytes token = 13;</code>
     * @return string
     */
    public function getToken()
    {
        return $this->token;
    }

    /**
     * Generated from protobuf field <code>optional bytes token = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setToken($var)
    {
        GPBUtil::checkString($var, False);
        $this->token = $var;
        $this->has_token = true;

        return $this;
    }

    public function hasToken()
    {
        return $this->has_token;
    }

    /**
     * Generated from protobuf field <code>optional string transaction_id = 14;</code>
     * @return string
     */
    public function getTransactionId()
    {
        return $this->transaction_id;
    }

    /**
     * Generated from protobuf field <code>optional string transaction_id = 14;</code>
     * @param string $var
     * @return $this
     */
    public function setTransactionId($var)
    {
        GPBUtil::checkString($var, True);
        $this->transaction_id = $var;
        $this->has_transaction_id = true;

        return $this;
    }

    public function hasTransactionId()
    {
        return $this->has_transaction_id;
    }

    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.DataBlockType data_block_type_hint = 15 [default = DBT_PLAIN_BUFFER];</code>
     * @return int
     */
    public function getDataBlockTypeHint()
    {
        return $this->data_block_type_hint;
    }

    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.DataBlockType data_block_type_hint = 15 [default = DBT_PLAIN_BUFFER];</code>
     * @param int $var
     * @return $this
     */
    public function setDataBlockTypeHint($var)
    {
        GPBUtil::checkEnum($var, \Aliyun\OTS\ProtoBuffer\Protocol\DataBlockType::class);
        $this->data_block_type_hint = $var;
        $this->has_data_block_type_hint = true;

        return $this;
    }

    public function hasDataBlockTypeHint()
    {
        return $this->has_data_block_type_hint;
    }

    /**
     * Generated from protobuf field <code>optional bool return_entire_primary_keys = 16 [default = true];</code>
     * @return bool
     */
    public function getReturnEntirePrimaryKeys()
    {
        return $this->return_entire_primary_keys;
    }

    /**
     * Generated from protobuf field <code>optional bool return_entire_primary_keys = 16 [default = true];</code>
     * @param bool $var
     * @return $this
     */
    public function setReturnEntirePrimaryKeys($var)
    {
        GPBUtil::checkBool($var);
        $this->return_entire_primary_keys = $var;
        $this->has_return_entire_primary_keys = true;

        return $this;
    }

    public function hasReturnEntirePrimaryKeys()
    {
        return $this->has_return_entire_primary_keys;
    }

    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.CompressType compress_type_hint = 17 [default = CPT_NONE];</code>
     * @return int
     */
    public function getCompressTypeHint()
    {
        return $this->compress_type_hint;
    }

    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.CompressType compress_type_hint = 17 [default = CPT_NONE];</code>
     * @param int $var
     * @return $this
     */
    public function setCompressTypeHint($var)
    {
        GPBUtil::checkEnum($var, \Aliyun\OTS\ProtoBuffer\Protocol\CompressType::class);
        $this->compress_type_hint = $var;
        $this->has_compress_type_hint = true;

        return $this;
    }

    public function hasCompressTypeHint()
    {
        return $this->has_compress_type_hint;
    }

}

