<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table_store.proto

namespace Aliyun\OTS\ProtoBuffer\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>aliyun.OTS.ProtoBuffer.Protocol.GetStreamRecordResponse</code>
 */
class GetStreamRecordResponse extends \Aliyun\OTS\ProtoBuffer\Protocol\Message
{
    /**
     * Generated from protobuf field <code>repeated .aliyun.OTS.ProtoBuffer.Protocol.GetStreamRecordResponse.StreamRecord stream_records = 1;</code>
     */
    private $stream_records;
    private $has_stream_records = false;
    /**
     * Generated from protobuf field <code>optional string next_shard_iterator = 2;</code>
     */
    private $next_shard_iterator = '';
    private $has_next_shard_iterator = false;

    public function __construct() {
        \GPBMetadata\TableStore::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>repeated .aliyun.OTS.ProtoBuffer.Protocol.GetStreamRecordResponse.StreamRecord stream_records = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getStreamRecords()
    {
        return $this->stream_records;
    }

    /**
     * Generated from protobuf field <code>repeated .aliyun.OTS.ProtoBuffer.Protocol.GetStreamRecordResponse.StreamRecord stream_records = 1;</code>
     * @param \Aliyun\OTS\ProtoBuffer\Protocol\GetStreamRecordResponse_StreamRecord[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setStreamRecords($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Aliyun\OTS\ProtoBuffer\Protocol\GetStreamRecordResponse_StreamRecord::class);
        $this->stream_records = $arr;
        $this->has_stream_records = true;

        return $this;
    }

    public function hasStreamRecords()
    {
        return $this->has_stream_records;
    }

    /**
     * Generated from protobuf field <code>optional string next_shard_iterator = 2;</code>
     * @return string
     */
    public function getNextShardIterator()
    {
        return $this->next_shard_iterator;
    }

    /**
     * Generated from protobuf field <code>optional string next_shard_iterator = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setNextShardIterator($var)
    {
        GPBUtil::checkString($var, True);
        $this->next_shard_iterator = $var;
        $this->has_next_shard_iterator = true;

        return $this;
    }

    public function hasNextShardIterator()
    {
        return $this->has_next_shard_iterator;
    }

}

