<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table_store.proto

namespace Aliyun\OTS\ProtoBuffer\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>aliyun.OTS.ProtoBuffer.Protocol.GetShardIteratorResponse</code>
 */
class GetShardIteratorResponse extends \Aliyun\OTS\ProtoBuffer\Protocol\Message
{
    /**
     * Generated from protobuf field <code>required string shard_iterator = 1;</code>
     */
    private $shard_iterator = '';
    private $has_shard_iterator = false;

    public function __construct() {
        \GPBMetadata\TableStore::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>required string shard_iterator = 1;</code>
     * @return string
     */
    public function getShardIterator()
    {
        return $this->shard_iterator;
    }

    /**
     * Generated from protobuf field <code>required string shard_iterator = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setShardIterator($var)
    {
        GPBUtil::checkString($var, True);
        $this->shard_iterator = $var;
        $this->has_shard_iterator = true;

        return $this;
    }

    public function hasShardIterator()
    {
        return $this->has_shard_iterator;
    }

}

