<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table_store_search.proto

namespace Aliyun\OTS\ProtoBuffer\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>aliyun.OTS.ProtoBuffer.Protocol.GroupByHistogramResult</code>
 */
class GroupByHistogramResult extends \Aliyun\OTS\ProtoBuffer\Protocol\Message
{
    /**
     * Generated from protobuf field <code>repeated .aliyun.OTS.ProtoBuffer.Protocol.GroupByHistogramItem group_by_histogram_items = 1;</code>
     */
    private $group_by_histogram_items;
    private $has_group_by_histogram_items = false;

    public function __construct() {
        \GPBMetadata\TableStoreSearch::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>repeated .aliyun.OTS.ProtoBuffer.Protocol.GroupByHistogramItem group_by_histogram_items = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getGroupByHistogramItems()
    {
        return $this->group_by_histogram_items;
    }

    /**
     * Generated from protobuf field <code>repeated .aliyun.OTS.ProtoBuffer.Protocol.GroupByHistogramItem group_by_histogram_items = 1;</code>
     * @param \Aliyun\OTS\ProtoBuffer\Protocol\GroupByHistogramItem[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setGroupByHistogramItems($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Aliyun\OTS\ProtoBuffer\Protocol\GroupByHistogramItem::class);
        $this->group_by_histogram_items = $arr;
        $this->has_group_by_histogram_items = true;

        return $this;
    }

    public function hasGroupByHistogramItems()
    {
        return $this->has_group_by_histogram_items;
    }

}

