<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table_store_search.proto

namespace Aliyun\OTS\ProtoBuffer\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>aliyun.OTS.ProtoBuffer.Protocol.GroupBys</code>
 */
class GroupBys extends \Aliyun\OTS\ProtoBuffer\Protocol\Message
{
    /**
     * Generated from protobuf field <code>repeated .aliyun.OTS.ProtoBuffer.Protocol.GroupBy group_bys = 1;</code>
     */
    private $group_bys;
    private $has_group_bys = false;

    public function __construct() {
        \GPBMetadata\TableStoreSearch::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>repeated .aliyun.OTS.ProtoBuffer.Protocol.GroupBy group_bys = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getGroupBys()
    {
        return $this->group_bys;
    }

    /**
     * Generated from protobuf field <code>repeated .aliyun.OTS.ProtoBuffer.Protocol.GroupBy group_bys = 1;</code>
     * @param \Aliyun\OTS\ProtoBuffer\Protocol\GroupBy[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setGroupBys($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Aliyun\OTS\ProtoBuffer\Protocol\GroupBy::class);
        $this->group_bys = $arr;
        $this->has_group_bys = true;

        return $this;
    }

    public function hasGroupBys()
    {
        return $this->has_group_bys;
    }

}

