<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table_store_search.proto

namespace Aliyun\OTS\ProtoBuffer\Protocol;

/**
 * Protobuf enum <code>Aliyun\OTS\ProtoBuffer\Protocol\GroupByType</code>
 */
class GroupByType
{
    /**
     * Generated from protobuf enum <code>GROUP_BY_FIELD = 1;</code>
     */
    const GROUP_BY_FIELD = 1;
    /**
     * Generated from protobuf enum <code>GROUP_BY_RANGE = 2;</code>
     */
    const GROUP_BY_RANGE = 2;
    /**
     * Generated from protobuf enum <code>GROUP_BY_FILTER = 3;</code>
     */
    const GROUP_BY_FILTER = 3;
    /**
     * Generated from protobuf enum <code>GROUP_BY_GEO_DISTANCE = 4;</code>
     */
    const GROUP_BY_GEO_DISTANCE = 4;
    /**
     * Generated from protobuf enum <code>GROUP_BY_HISTOGRAM = 5;</code>
     */
    const GROUP_BY_HISTOGRAM = 5;
    /**
     * Generated from protobuf enum <code>GROUP_BY_DATE_HISTOGRAM = 6;</code>
     */
    const GROUP_BY_DATE_HISTOGRAM = 6;
    /**
     * Generated from protobuf enum <code>GROUP_BY_GEO_GRID = 7;</code>
     */
    const GROUP_BY_GEO_GRID = 7;
    /**
     * Generated from protobuf enum <code>GROUP_BY_COMPOSITE = 8;</code>
     */
    const GROUP_BY_COMPOSITE = 8;
}

