<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table_store_search.proto

namespace Aliyun\OTS\ProtoBuffer\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>aliyun.OTS.ProtoBuffer.Protocol.Highlight</code>
 */
class Highlight extends \Aliyun\OTS\ProtoBuffer\Protocol\Message
{
    /**
     * Generated from protobuf field <code>repeated .aliyun.OTS.ProtoBuffer.Protocol.HighlightParameter highlight_parameters = 1;</code>
     */
    private $highlight_parameters;
    private $has_highlight_parameters = false;
    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.HighlightEncoder highlight_encoder = 2 [default = PLAIN_MODE];</code>
     */
    private $highlight_encoder = 0;
    private $has_highlight_encoder = false;

    public function __construct() {
        \GPBMetadata\TableStoreSearch::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>repeated .aliyun.OTS.ProtoBuffer.Protocol.HighlightParameter highlight_parameters = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getHighlightParameters()
    {
        return $this->highlight_parameters;
    }

    /**
     * Generated from protobuf field <code>repeated .aliyun.OTS.ProtoBuffer.Protocol.HighlightParameter highlight_parameters = 1;</code>
     * @param \Aliyun\OTS\ProtoBuffer\Protocol\HighlightParameter[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setHighlightParameters($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Aliyun\OTS\ProtoBuffer\Protocol\HighlightParameter::class);
        $this->highlight_parameters = $arr;
        $this->has_highlight_parameters = true;

        return $this;
    }

    public function hasHighlightParameters()
    {
        return $this->has_highlight_parameters;
    }

    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.HighlightEncoder highlight_encoder = 2 [default = PLAIN_MODE];</code>
     * @return int
     */
    public function getHighlightEncoder()
    {
        return $this->highlight_encoder;
    }

    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.HighlightEncoder highlight_encoder = 2 [default = PLAIN_MODE];</code>
     * @param int $var
     * @return $this
     */
    public function setHighlightEncoder($var)
    {
        GPBUtil::checkEnum($var, \Aliyun\OTS\ProtoBuffer\Protocol\HighlightEncoder::class);
        $this->highlight_encoder = $var;
        $this->has_highlight_encoder = true;

        return $this;
    }

    public function hasHighlightEncoder()
    {
        return $this->has_highlight_encoder;
    }

}

