<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table_store_search.proto

namespace Aliyun\OTS\ProtoBuffer\Protocol;

/**
 * Protobuf enum <code>Aliyun\OTS\ProtoBuffer\Protocol\HighlightFragmentOrder</code>
 */
class HighlightFragmentOrder
{
    /**
     * Generated from protobuf enum <code>TEXT_SEQUENCE = 1;</code>
     */
    const TEXT_SEQUENCE = 1;
    /**
     * Generated from protobuf enum <code>SCORE = 2;</code>
     */
    const SCORE = 2;
}

