<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table_store_search.proto

namespace Aliyun\OTS\ProtoBuffer\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>aliyun.OTS.ProtoBuffer.Protocol.IndexSchema</code>
 */
class IndexSchema extends \Aliyun\OTS\ProtoBuffer\Protocol\Message
{
    /**
     * Generated from protobuf field <code>repeated .aliyun.OTS.ProtoBuffer.Protocol.FieldSchema field_schemas = 1;</code>
     */
    private $field_schemas;
    private $has_field_schemas = false;
    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.IndexSetting index_setting = 2;</code>
     */
    private $index_setting = null;
    private $has_index_setting = false;
    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.Sort index_sort = 3;</code>
     */
    private $index_sort = null;
    private $has_index_sort = false;

    public function __construct() {
        \GPBMetadata\TableStoreSearch::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>repeated .aliyun.OTS.ProtoBuffer.Protocol.FieldSchema field_schemas = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFieldSchemas()
    {
        return $this->field_schemas;
    }

    /**
     * Generated from protobuf field <code>repeated .aliyun.OTS.ProtoBuffer.Protocol.FieldSchema field_schemas = 1;</code>
     * @param \Aliyun\OTS\ProtoBuffer\Protocol\FieldSchema[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFieldSchemas($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Aliyun\OTS\ProtoBuffer\Protocol\FieldSchema::class);
        $this->field_schemas = $arr;
        $this->has_field_schemas = true;

        return $this;
    }

    public function hasFieldSchemas()
    {
        return $this->has_field_schemas;
    }

    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.IndexSetting index_setting = 2;</code>
     * @return \Aliyun\OTS\ProtoBuffer\Protocol\IndexSetting
     */
    public function getIndexSetting()
    {
        return $this->index_setting;
    }

    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.IndexSetting index_setting = 2;</code>
     * @param \Aliyun\OTS\ProtoBuffer\Protocol\IndexSetting $var
     * @return $this
     */
    public function setIndexSetting($var)
    {
        GPBUtil::checkMessage($var, \Aliyun\OTS\ProtoBuffer\Protocol\IndexSetting::class);
        $this->index_setting = $var;
        $this->has_index_setting = true;

        return $this;
    }

    public function hasIndexSetting()
    {
        return $this->has_index_setting;
    }

    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.Sort index_sort = 3;</code>
     * @return \Aliyun\OTS\ProtoBuffer\Protocol\Sort
     */
    public function getIndexSort()
    {
        return $this->index_sort;
    }

    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.Sort index_sort = 3;</code>
     * @param \Aliyun\OTS\ProtoBuffer\Protocol\Sort $var
     * @return $this
     */
    public function setIndexSort($var)
    {
        GPBUtil::checkMessage($var, \Aliyun\OTS\ProtoBuffer\Protocol\Sort::class);
        $this->index_sort = $var;
        $this->has_index_sort = true;

        return $this;
    }

    public function hasIndexSort()
    {
        return $this->has_index_sort;
    }

}

