<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table_store.proto

namespace Aliyun\OTS\ProtoBuffer\Protocol;

/**
 * Protobuf enum <code>Aliyun\OTS\ProtoBuffer\Protocol\IndexSyncPhase</code>
 */
class IndexSyncPhase
{
    /**
     * Generated from protobuf enum <code>ISP_INVALID = 0;</code>
     */
    const ISP_INVALID = 0;
    /**
     * Generated from protobuf enum <code>ISP_FULL = 1;</code>
     */
    const ISP_FULL = 1;
    /**
     * Generated from protobuf enum <code>ISP_INCR = 2;</code>
     */
    const ISP_INCR = 2;
}

