<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table_store_search.proto

namespace Aliyun\OTS\ProtoBuffer\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>aliyun.OTS.ProtoBuffer.Protocol.IndexStatus</code>
 */
class IndexStatus extends \Aliyun\OTS\ProtoBuffer\Protocol\Message
{
    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.IndexStatusEnum status = 1;</code>
     */
    private $status = 0;
    private $has_status = false;
    /**
     * Generated from protobuf field <code>optional string status_description = 2;</code>
     */
    private $status_description = '';
    private $has_status_description = false;

    public function __construct() {
        \GPBMetadata\TableStoreSearch::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.IndexStatusEnum status = 1;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.IndexStatusEnum status = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \Aliyun\OTS\ProtoBuffer\Protocol\IndexStatusEnum::class);
        $this->status = $var;
        $this->has_status = true;

        return $this;
    }

    public function hasStatus()
    {
        return $this->has_status;
    }

    /**
     * Generated from protobuf field <code>optional string status_description = 2;</code>
     * @return string
     */
    public function getStatusDescription()
    {
        return $this->status_description;
    }

    /**
     * Generated from protobuf field <code>optional string status_description = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setStatusDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->status_description = $var;
        $this->has_status_description = true;

        return $this;
    }

    public function hasStatusDescription()
    {
        return $this->has_status_description;
    }

}

