<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table_store.proto

namespace Aliyun\OTS\ProtoBuffer\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>aliyun.OTS.ProtoBuffer.Protocol.IndexMeta</code>
 */
class IndexMeta extends \Aliyun\OTS\ProtoBuffer\Protocol\Message
{
    /**
     * Generated from protobuf field <code>required string name = 1;</code>
     */
    private $name = '';
    private $has_name = false;
    /**
     * Generated from protobuf field <code>repeated string primary_key = 2;</code>
     */
    private $primary_key;
    private $has_primary_key = false;
    /**
     * Generated from protobuf field <code>repeated string defined_column = 3;</code>
     */
    private $defined_column;
    private $has_defined_column = false;
    /**
     * Generated from protobuf field <code>required .aliyun.OTS.ProtoBuffer.Protocol.IndexUpdateMode index_update_mode = 4;</code>
     */
    private $index_update_mode = 0;
    private $has_index_update_mode = false;
    /**
     * Generated from protobuf field <code>required .aliyun.OTS.ProtoBuffer.Protocol.IndexType index_type = 5;</code>
     */
    private $index_type = 0;
    private $has_index_type = false;

    public function __construct() {
        \GPBMetadata\TableStore::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>required string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>required string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;
        $this->has_name = true;

        return $this;
    }

    public function hasName()
    {
        return $this->has_name;
    }

    /**
     * Generated from protobuf field <code>repeated string primary_key = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPrimaryKey()
    {
        return $this->primary_key;
    }

    /**
     * Generated from protobuf field <code>repeated string primary_key = 2;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPrimaryKey($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->primary_key = $arr;
        $this->has_primary_key = true;

        return $this;
    }

    public function hasPrimaryKey()
    {
        return $this->has_primary_key;
    }

    /**
     * Generated from protobuf field <code>repeated string defined_column = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDefinedColumn()
    {
        return $this->defined_column;
    }

    /**
     * Generated from protobuf field <code>repeated string defined_column = 3;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDefinedColumn($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->defined_column = $arr;
        $this->has_defined_column = true;

        return $this;
    }

    public function hasDefinedColumn()
    {
        return $this->has_defined_column;
    }

    /**
     * Generated from protobuf field <code>required .aliyun.OTS.ProtoBuffer.Protocol.IndexUpdateMode index_update_mode = 4;</code>
     * @return int
     */
    public function getIndexUpdateMode()
    {
        return $this->index_update_mode;
    }

    /**
     * Generated from protobuf field <code>required .aliyun.OTS.ProtoBuffer.Protocol.IndexUpdateMode index_update_mode = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setIndexUpdateMode($var)
    {
        GPBUtil::checkEnum($var, \Aliyun\OTS\ProtoBuffer\Protocol\IndexUpdateMode::class);
        $this->index_update_mode = $var;
        $this->has_index_update_mode = true;

        return $this;
    }

    public function hasIndexUpdateMode()
    {
        return $this->has_index_update_mode;
    }

    /**
     * Generated from protobuf field <code>required .aliyun.OTS.ProtoBuffer.Protocol.IndexType index_type = 5;</code>
     * @return int
     */
    public function getIndexType()
    {
        return $this->index_type;
    }

    /**
     * Generated from protobuf field <code>required .aliyun.OTS.ProtoBuffer.Protocol.IndexType index_type = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setIndexType($var)
    {
        GPBUtil::checkEnum($var, \Aliyun\OTS\ProtoBuffer\Protocol\IndexType::class);
        $this->index_type = $var;
        $this->has_index_type = true;

        return $this;
    }

    public function hasIndexType()
    {
        return $this->has_index_type;
    }

}

