<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table_store_search.proto

namespace Aliyun\OTS\ProtoBuffer\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>aliyun.OTS.ProtoBuffer.Protocol.InnerHits</code>
 */
class InnerHits extends \Aliyun\OTS\ProtoBuffer\Protocol\Message
{
    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.Sort sort = 1;</code>
     */
    private $sort = null;
    private $has_sort = false;
    /**
     * Generated from protobuf field <code>optional int32 offset = 2;</code>
     */
    private $offset = 0;
    private $has_offset = false;
    /**
     * Generated from protobuf field <code>optional int32 limit = 3;</code>
     */
    private $limit = 0;
    private $has_limit = false;
    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.Highlight highlight = 4;</code>
     */
    private $highlight = null;
    private $has_highlight = false;

    public function __construct() {
        \GPBMetadata\TableStoreSearch::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.Sort sort = 1;</code>
     * @return \Aliyun\OTS\ProtoBuffer\Protocol\Sort
     */
    public function getSort()
    {
        return $this->sort;
    }

    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.Sort sort = 1;</code>
     * @param \Aliyun\OTS\ProtoBuffer\Protocol\Sort $var
     * @return $this
     */
    public function setSort($var)
    {
        GPBUtil::checkMessage($var, \Aliyun\OTS\ProtoBuffer\Protocol\Sort::class);
        $this->sort = $var;
        $this->has_sort = true;

        return $this;
    }

    public function hasSort()
    {
        return $this->has_sort;
    }

    /**
     * Generated from protobuf field <code>optional int32 offset = 2;</code>
     * @return int
     */
    public function getOffset()
    {
        return $this->offset;
    }

    /**
     * Generated from protobuf field <code>optional int32 offset = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setOffset($var)
    {
        GPBUtil::checkInt32($var);
        $this->offset = $var;
        $this->has_offset = true;

        return $this;
    }

    public function hasOffset()
    {
        return $this->has_offset;
    }

    /**
     * Generated from protobuf field <code>optional int32 limit = 3;</code>
     * @return int
     */
    public function getLimit()
    {
        return $this->limit;
    }

    /**
     * Generated from protobuf field <code>optional int32 limit = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setLimit($var)
    {
        GPBUtil::checkInt32($var);
        $this->limit = $var;
        $this->has_limit = true;

        return $this;
    }

    public function hasLimit()
    {
        return $this->has_limit;
    }

    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.Highlight highlight = 4;</code>
     * @return \Aliyun\OTS\ProtoBuffer\Protocol\Highlight
     */
    public function getHighlight()
    {
        return $this->highlight;
    }

    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.Highlight highlight = 4;</code>
     * @param \Aliyun\OTS\ProtoBuffer\Protocol\Highlight $var
     * @return $this
     */
    public function setHighlight($var)
    {
        GPBUtil::checkMessage($var, \Aliyun\OTS\ProtoBuffer\Protocol\Highlight::class);
        $this->highlight = $var;
        $this->has_highlight = true;

        return $this;
    }

    public function hasHighlight()
    {
        return $this->has_highlight;
    }

}

