<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table_store_search.proto

namespace Aliyun\OTS\ProtoBuffer\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>aliyun.OTS.ProtoBuffer.Protocol.KnnVectorQuery</code>
 */
class KnnVectorQuery extends \Aliyun\OTS\ProtoBuffer\Protocol\Message
{
    /**
     * Generated from protobuf field <code>optional string field_name = 1;</code>
     */
    private $field_name = '';
    private $has_field_name = false;
    /**
     * Generated from protobuf field <code>optional int32 top_k = 2;</code>
     */
    private $top_k = 0;
    private $has_top_k = false;
    /**
     * Generated from protobuf field <code>repeated float float32_query_vector = 4;</code>
     */
    private $float32_query_vector;
    private $has_float32_query_vector = false;
    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.Query filter = 5;</code>
     */
    private $filter = null;
    private $has_filter = false;
    /**
     * Generated from protobuf field <code>optional float weight = 6;</code>
     */
    private $weight = 0.0;
    private $has_weight = false;

    public function __construct() {
        \GPBMetadata\TableStoreSearch::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>optional string field_name = 1;</code>
     * @return string
     */
    public function getFieldName()
    {
        return $this->field_name;
    }

    /**
     * Generated from protobuf field <code>optional string field_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setFieldName($var)
    {
        GPBUtil::checkString($var, True);
        $this->field_name = $var;
        $this->has_field_name = true;

        return $this;
    }

    public function hasFieldName()
    {
        return $this->has_field_name;
    }

    /**
     * Generated from protobuf field <code>optional int32 top_k = 2;</code>
     * @return int
     */
    public function getTopK()
    {
        return $this->top_k;
    }

    /**
     * Generated from protobuf field <code>optional int32 top_k = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setTopK($var)
    {
        GPBUtil::checkInt32($var);
        $this->top_k = $var;
        $this->has_top_k = true;

        return $this;
    }

    public function hasTopK()
    {
        return $this->has_top_k;
    }

    /**
     * Generated from protobuf field <code>repeated float float32_query_vector = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFloat32QueryVector()
    {
        return $this->float32_query_vector;
    }

    /**
     * Generated from protobuf field <code>repeated float float32_query_vector = 4;</code>
     * @param float[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFloat32QueryVector($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::FLOAT);
        $this->float32_query_vector = $arr;
        $this->has_float32_query_vector = true;

        return $this;
    }

    public function hasFloat32QueryVector()
    {
        return $this->has_float32_query_vector;
    }

    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.Query filter = 5;</code>
     * @return \Aliyun\OTS\ProtoBuffer\Protocol\Query
     */
    public function getFilter()
    {
        return $this->filter;
    }

    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.Query filter = 5;</code>
     * @param \Aliyun\OTS\ProtoBuffer\Protocol\Query $var
     * @return $this
     */
    public function setFilter($var)
    {
        GPBUtil::checkMessage($var, \Aliyun\OTS\ProtoBuffer\Protocol\Query::class);
        $this->filter = $var;
        $this->has_filter = true;

        return $this;
    }

    public function hasFilter()
    {
        return $this->has_filter;
    }

    /**
     * Generated from protobuf field <code>optional float weight = 6;</code>
     * @return float
     */
    public function getWeight()
    {
        return $this->weight;
    }

    /**
     * Generated from protobuf field <code>optional float weight = 6;</code>
     * @param float $var
     * @return $this
     */
    public function setWeight($var)
    {
        GPBUtil::checkFloat($var);
        $this->weight = $var;
        $this->has_weight = true;

        return $this;
    }

    public function hasWeight()
    {
        return $this->has_weight;
    }

}

