<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table_store_search.proto

namespace Aliyun\OTS\ProtoBuffer\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>aliyun.OTS.ProtoBuffer.Protocol.ListSearchIndexResponse</code>
 */
class ListSearchIndexResponse extends \Aliyun\OTS\ProtoBuffer\Protocol\Message
{
    /**
     * Generated from protobuf field <code>repeated .aliyun.OTS.ProtoBuffer.Protocol.IndexInfo indices = 1;</code>
     */
    private $indices;
    private $has_indices = false;

    public function __construct() {
        \GPBMetadata\TableStoreSearch::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>repeated .aliyun.OTS.ProtoBuffer.Protocol.IndexInfo indices = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getIndices()
    {
        return $this->indices;
    }

    /**
     * Generated from protobuf field <code>repeated .aliyun.OTS.ProtoBuffer.Protocol.IndexInfo indices = 1;</code>
     * @param \Aliyun\OTS\ProtoBuffer\Protocol\IndexInfo[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setIndices($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Aliyun\OTS\ProtoBuffer\Protocol\IndexInfo::class);
        $this->indices = $arr;
        $this->has_indices = true;

        return $this;
    }

    public function hasIndices()
    {
        return $this->has_indices;
    }

}

