<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table_store_filter.proto

namespace Aliyun\OTS\ProtoBuffer\Protocol;

/**
 * Protobuf enum <code>Aliyun\OTS\ProtoBuffer\Protocol\LogicalOperator</code>
 */
class LogicalOperator
{
    /**
     * Generated from protobuf enum <code>LO_NOT = 1;</code>
     */
    const LO_NOT = 1;
    /**
     * Generated from protobuf enum <code>LO_AND = 2;</code>
     */
    const LO_AND = 2;
    /**
     * Generated from protobuf enum <code>LO_OR = 3;</code>
     */
    const LO_OR = 3;
}

