<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table_store_search.proto

namespace Aliyun\OTS\ProtoBuffer\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>aliyun.OTS.ProtoBuffer.Protocol.MeteringInfo</code>
 */
class MeteringInfo extends \Aliyun\OTS\ProtoBuffer\Protocol\Message
{
    /**
     * Generated from protobuf field <code>optional int64 storage_size = 1;</code>
     */
    private $storage_size = 0;
    private $has_storage_size = false;
    /**
     * Generated from protobuf field <code>optional int64 row_count = 2;</code>
     */
    private $row_count = 0;
    private $has_row_count = false;
    /**
     * Generated from protobuf field <code>optional int64 reserved_read_cu = 3;</code>
     */
    private $reserved_read_cu = 0;
    private $has_reserved_read_cu = false;
    /**
     * Generated from protobuf field <code>optional int64 timestamp = 4;</code>
     */
    private $timestamp = 0;
    private $has_timestamp = false;

    public function __construct() {
        \GPBMetadata\TableStoreSearch::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>optional int64 storage_size = 1;</code>
     * @return int|string
     */
    public function getStorageSize()
    {
        return $this->storage_size;
    }

    /**
     * Generated from protobuf field <code>optional int64 storage_size = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setStorageSize($var)
    {
        GPBUtil::checkInt64($var);
        $this->storage_size = $var;
        $this->has_storage_size = true;

        return $this;
    }

    public function hasStorageSize()
    {
        return $this->has_storage_size;
    }

    /**
     * Generated from protobuf field <code>optional int64 row_count = 2;</code>
     * @return int|string
     */
    public function getRowCount()
    {
        return $this->row_count;
    }

    /**
     * Generated from protobuf field <code>optional int64 row_count = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRowCount($var)
    {
        GPBUtil::checkInt64($var);
        $this->row_count = $var;
        $this->has_row_count = true;

        return $this;
    }

    public function hasRowCount()
    {
        return $this->has_row_count;
    }

    /**
     * Generated from protobuf field <code>optional int64 reserved_read_cu = 3;</code>
     * @return int|string
     */
    public function getReservedReadCu()
    {
        return $this->reserved_read_cu;
    }

    /**
     * Generated from protobuf field <code>optional int64 reserved_read_cu = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setReservedReadCu($var)
    {
        GPBUtil::checkInt64($var);
        $this->reserved_read_cu = $var;
        $this->has_reserved_read_cu = true;

        return $this;
    }

    public function hasReservedReadCu()
    {
        return $this->has_reserved_read_cu;
    }

    /**
     * Generated from protobuf field <code>optional int64 timestamp = 4;</code>
     * @return int|string
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * Generated from protobuf field <code>optional int64 timestamp = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkInt64($var);
        $this->timestamp = $var;
        $this->has_timestamp = true;

        return $this;
    }

    public function hasTimestamp()
    {
        return $this->has_timestamp;
    }

}

