<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table_store_search.proto

namespace Aliyun\OTS\ProtoBuffer\Protocol;

/**
 * Protobuf enum <code>Aliyun\OTS\ProtoBuffer\Protocol\MultiValueMode</code>
 */
class MultiValueMode
{
    /**
     * Generated from protobuf enum <code>MVM_MAX = 1;</code>
     */
    const MVM_MAX = 1;
    /**
     * Generated from protobuf enum <code>MVM_MIN = 2;</code>
     */
    const MVM_MIN = 2;
    /**
     * Generated from protobuf enum <code>MVM_SUM = 3;</code>
     */
    const MVM_SUM = 3;
    /**
     * Generated from protobuf enum <code>MVM_AVG = 4;</code>
     */
    const MVM_AVG = 4;
}

