<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table_store_search.proto

namespace Aliyun\OTS\ProtoBuffer\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>aliyun.OTS.ProtoBuffer.Protocol.NestedQuery</code>
 */
class NestedQuery extends \Aliyun\OTS\ProtoBuffer\Protocol\Message
{
    /**
     * Generated from protobuf field <code>optional string path = 1;</code>
     */
    private $path = '';
    private $has_path = false;
    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.Query query = 2;</code>
     */
    private $query = null;
    private $has_query = false;
    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.ScoreMode score_mode = 3;</code>
     */
    private $score_mode = 0;
    private $has_score_mode = false;
    /**
     * Generated from protobuf field <code>optional float weight = 4;</code>
     */
    private $weight = 0.0;
    private $has_weight = false;

    public function __construct() {
        \GPBMetadata\TableStoreSearch::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>optional string path = 1;</code>
     * @return string
     */
    public function getPath()
    {
        return $this->path;
    }

    /**
     * Generated from protobuf field <code>optional string path = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPath($var)
    {
        GPBUtil::checkString($var, True);
        $this->path = $var;
        $this->has_path = true;

        return $this;
    }

    public function hasPath()
    {
        return $this->has_path;
    }

    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.Query query = 2;</code>
     * @return \Aliyun\OTS\ProtoBuffer\Protocol\Query
     */
    public function getQuery()
    {
        return $this->query;
    }

    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.Query query = 2;</code>
     * @param \Aliyun\OTS\ProtoBuffer\Protocol\Query $var
     * @return $this
     */
    public function setQuery($var)
    {
        GPBUtil::checkMessage($var, \Aliyun\OTS\ProtoBuffer\Protocol\Query::class);
        $this->query = $var;
        $this->has_query = true;

        return $this;
    }

    public function hasQuery()
    {
        return $this->has_query;
    }

    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.ScoreMode score_mode = 3;</code>
     * @return int
     */
    public function getScoreMode()
    {
        return $this->score_mode;
    }

    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.ScoreMode score_mode = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setScoreMode($var)
    {
        GPBUtil::checkEnum($var, \Aliyun\OTS\ProtoBuffer\Protocol\ScoreMode::class);
        $this->score_mode = $var;
        $this->has_score_mode = true;

        return $this;
    }

    public function hasScoreMode()
    {
        return $this->has_score_mode;
    }

    /**
     * Generated from protobuf field <code>optional float weight = 4;</code>
     * @return float
     */
    public function getWeight()
    {
        return $this->weight;
    }

    /**
     * Generated from protobuf field <code>optional float weight = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setWeight($var)
    {
        GPBUtil::checkFloat($var);
        $this->weight = $var;
        $this->has_weight = true;

        return $this;
    }

    public function hasWeight()
    {
        return $this->has_weight;
    }

}

