<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table_store_search.proto

namespace Aliyun\OTS\ProtoBuffer\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>aliyun.OTS.ProtoBuffer.Protocol.ParallelScanRequest</code>
 */
class ParallelScanRequest extends \Aliyun\OTS\ProtoBuffer\Protocol\Message
{
    /**
     * Generated from protobuf field <code>optional string table_name = 1;</code>
     */
    private $table_name = '';
    private $has_table_name = false;
    /**
     * Generated from protobuf field <code>optional string index_name = 2;</code>
     */
    private $index_name = '';
    private $has_index_name = false;
    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.ColumnsToGet columns_to_get = 3;</code>
     */
    private $columns_to_get = null;
    private $has_columns_to_get = false;
    /**
     * Generated from protobuf field <code>optional bytes session_id = 4;</code>
     */
    private $session_id = '';
    private $has_session_id = false;
    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.ScanQuery scan_query = 5;</code>
     */
    private $scan_query = null;
    private $has_scan_query = false;
    /**
     * Generated from protobuf field <code>optional int32 timeout_ms = 6;</code>
     */
    private $timeout_ms = 0;
    private $has_timeout_ms = false;

    public function __construct() {
        \GPBMetadata\TableStoreSearch::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>optional string table_name = 1;</code>
     * @return string
     */
    public function getTableName()
    {
        return $this->table_name;
    }

    /**
     * Generated from protobuf field <code>optional string table_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTableName($var)
    {
        GPBUtil::checkString($var, True);
        $this->table_name = $var;
        $this->has_table_name = true;

        return $this;
    }

    public function hasTableName()
    {
        return $this->has_table_name;
    }

    /**
     * Generated from protobuf field <code>optional string index_name = 2;</code>
     * @return string
     */
    public function getIndexName()
    {
        return $this->index_name;
    }

    /**
     * Generated from protobuf field <code>optional string index_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setIndexName($var)
    {
        GPBUtil::checkString($var, True);
        $this->index_name = $var;
        $this->has_index_name = true;

        return $this;
    }

    public function hasIndexName()
    {
        return $this->has_index_name;
    }

    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.ColumnsToGet columns_to_get = 3;</code>
     * @return \Aliyun\OTS\ProtoBuffer\Protocol\ColumnsToGet
     */
    public function getColumnsToGet()
    {
        return $this->columns_to_get;
    }

    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.ColumnsToGet columns_to_get = 3;</code>
     * @param \Aliyun\OTS\ProtoBuffer\Protocol\ColumnsToGet $var
     * @return $this
     */
    public function setColumnsToGet($var)
    {
        GPBUtil::checkMessage($var, \Aliyun\OTS\ProtoBuffer\Protocol\ColumnsToGet::class);
        $this->columns_to_get = $var;
        $this->has_columns_to_get = true;

        return $this;
    }

    public function hasColumnsToGet()
    {
        return $this->has_columns_to_get;
    }

    /**
     * Generated from protobuf field <code>optional bytes session_id = 4;</code>
     * @return string
     */
    public function getSessionId()
    {
        return $this->session_id;
    }

    /**
     * Generated from protobuf field <code>optional bytes session_id = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setSessionId($var)
    {
        GPBUtil::checkString($var, False);
        $this->session_id = $var;
        $this->has_session_id = true;

        return $this;
    }

    public function hasSessionId()
    {
        return $this->has_session_id;
    }

    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.ScanQuery scan_query = 5;</code>
     * @return \Aliyun\OTS\ProtoBuffer\Protocol\ScanQuery
     */
    public function getScanQuery()
    {
        return $this->scan_query;
    }

    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.ScanQuery scan_query = 5;</code>
     * @param \Aliyun\OTS\ProtoBuffer\Protocol\ScanQuery $var
     * @return $this
     */
    public function setScanQuery($var)
    {
        GPBUtil::checkMessage($var, \Aliyun\OTS\ProtoBuffer\Protocol\ScanQuery::class);
        $this->scan_query = $var;
        $this->has_scan_query = true;

        return $this;
    }

    public function hasScanQuery()
    {
        return $this->has_scan_query;
    }

    /**
     * Generated from protobuf field <code>optional int32 timeout_ms = 6;</code>
     * @return int
     */
    public function getTimeoutMs()
    {
        return $this->timeout_ms;
    }

    /**
     * Generated from protobuf field <code>optional int32 timeout_ms = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setTimeoutMs($var)
    {
        GPBUtil::checkInt32($var);
        $this->timeout_ms = $var;
        $this->has_timeout_ms = true;

        return $this;
    }

    public function hasTimeoutMs()
    {
        return $this->has_timeout_ms;
    }

}

