<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table_store_search.proto

namespace Aliyun\OTS\ProtoBuffer\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>aliyun.OTS.ProtoBuffer.Protocol.Function</code>
 */
class PBFunction extends \Aliyun\OTS\ProtoBuffer\Protocol\Message
{
    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.FieldValueFactorFunction field_value_factor = 1;</code>
     */
    private $field_value_factor = null;
    private $has_field_value_factor = false;
    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.RandomScoreFunction random = 2;</code>
     */
    private $random = null;
    private $has_random = false;
    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.DecayFunction decay = 3;</code>
     */
    private $decay = null;
    private $has_decay = false;
    /**
     * Generated from protobuf field <code>optional float weight = 4;</code>
     */
    private $weight = 0.0;
    private $has_weight = false;
    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.Query filter = 5;</code>
     */
    private $filter = null;
    private $has_filter = false;

    public function __construct() {
        \GPBMetadata\TableStoreSearch::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.FieldValueFactorFunction field_value_factor = 1;</code>
     * @return \Aliyun\OTS\ProtoBuffer\Protocol\FieldValueFactorFunction
     */
    public function getFieldValueFactor()
    {
        return $this->field_value_factor;
    }

    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.FieldValueFactorFunction field_value_factor = 1;</code>
     * @param \Aliyun\OTS\ProtoBuffer\Protocol\FieldValueFactorFunction $var
     * @return $this
     */
    public function setFieldValueFactor($var)
    {
        GPBUtil::checkMessage($var, \Aliyun\OTS\ProtoBuffer\Protocol\FieldValueFactorFunction::class);
        $this->field_value_factor = $var;
        $this->has_field_value_factor = true;

        return $this;
    }

    public function hasFieldValueFactor()
    {
        return $this->has_field_value_factor;
    }

    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.RandomScoreFunction random = 2;</code>
     * @return \Aliyun\OTS\ProtoBuffer\Protocol\RandomScoreFunction
     */
    public function getRandom()
    {
        return $this->random;
    }

    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.RandomScoreFunction random = 2;</code>
     * @param \Aliyun\OTS\ProtoBuffer\Protocol\RandomScoreFunction $var
     * @return $this
     */
    public function setRandom($var)
    {
        GPBUtil::checkMessage($var, \Aliyun\OTS\ProtoBuffer\Protocol\RandomScoreFunction::class);
        $this->random = $var;
        $this->has_random = true;

        return $this;
    }

    public function hasRandom()
    {
        return $this->has_random;
    }

    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.DecayFunction decay = 3;</code>
     * @return \Aliyun\OTS\ProtoBuffer\Protocol\DecayFunction
     */
    public function getDecay()
    {
        return $this->decay;
    }

    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.DecayFunction decay = 3;</code>
     * @param \Aliyun\OTS\ProtoBuffer\Protocol\DecayFunction $var
     * @return $this
     */
    public function setDecay($var)
    {
        GPBUtil::checkMessage($var, \Aliyun\OTS\ProtoBuffer\Protocol\DecayFunction::class);
        $this->decay = $var;
        $this->has_decay = true;

        return $this;
    }

    public function hasDecay()
    {
        return $this->has_decay;
    }

    /**
     * Generated from protobuf field <code>optional float weight = 4;</code>
     * @return float
     */
    public function getWeight()
    {
        return $this->weight;
    }

    /**
     * Generated from protobuf field <code>optional float weight = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setWeight($var)
    {
        GPBUtil::checkFloat($var);
        $this->weight = $var;
        $this->has_weight = true;

        return $this;
    }

    public function hasWeight()
    {
        return $this->has_weight;
    }

    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.Query filter = 5;</code>
     * @return \Aliyun\OTS\ProtoBuffer\Protocol\Query
     */
    public function getFilter()
    {
        return $this->filter;
    }

    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.Query filter = 5;</code>
     * @param \Aliyun\OTS\ProtoBuffer\Protocol\Query $var
     * @return $this
     */
    public function setFilter($var)
    {
        GPBUtil::checkMessage($var, \Aliyun\OTS\ProtoBuffer\Protocol\Query::class);
        $this->filter = $var;
        $this->has_filter = true;

        return $this;
    }

    public function hasFilter()
    {
        return $this->has_filter;
    }

}

