<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table_store_search.proto

namespace Aliyun\OTS\ProtoBuffer\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>aliyun.OTS.ProtoBuffer.Protocol.PercentilesAggregationResult</code>
 */
class PercentilesAggregationResult extends \Aliyun\OTS\ProtoBuffer\Protocol\Message
{
    /**
     * Generated from protobuf field <code>repeated .aliyun.OTS.ProtoBuffer.Protocol.PercentilesAggregationItem percentiles_aggregation_items = 1;</code>
     */
    private $percentiles_aggregation_items;
    private $has_percentiles_aggregation_items = false;

    public function __construct() {
        \GPBMetadata\TableStoreSearch::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>repeated .aliyun.OTS.ProtoBuffer.Protocol.PercentilesAggregationItem percentiles_aggregation_items = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPercentilesAggregationItems()
    {
        return $this->percentiles_aggregation_items;
    }

    /**
     * Generated from protobuf field <code>repeated .aliyun.OTS.ProtoBuffer.Protocol.PercentilesAggregationItem percentiles_aggregation_items = 1;</code>
     * @param \Aliyun\OTS\ProtoBuffer\Protocol\PercentilesAggregationItem[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPercentilesAggregationItems($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Aliyun\OTS\ProtoBuffer\Protocol\PercentilesAggregationItem::class);
        $this->percentiles_aggregation_items = $arr;
        $this->has_percentiles_aggregation_items = true;

        return $this;
    }

    public function hasPercentilesAggregationItems()
    {
        return $this->has_percentiles_aggregation_items;
    }

}

