<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table_store.proto

namespace Aliyun\OTS\ProtoBuffer\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 **
 * 这里允许用户为每列单独设置timestamp，而不是强制整行统一一个timestamp。
 * 原因是列都是用统一的结构，该结构本身是带timestamp的，其次强制统一timestamp增强了规范性但是丧失了灵活性，且该规范性没有明显的好处，反而带来了结构的复杂。
 *
 * Generated from protobuf message <code>aliyun.OTS.ProtoBuffer.Protocol.PutRowRequest</code>
 */
class PutRowRequest extends \Aliyun\OTS\ProtoBuffer\Protocol\Message
{
    /**
     * Generated from protobuf field <code>required string table_name = 1;</code>
     */
    private $table_name = '';
    private $has_table_name = false;
    /**
     * encoded as InplaceRowChangeSet
     *
     * Generated from protobuf field <code>required bytes row = 2;</code>
     */
    private $row = '';
    private $has_row = false;
    /**
     * Generated from protobuf field <code>required .aliyun.OTS.ProtoBuffer.Protocol.Condition condition = 3;</code>
     */
    private $condition = null;
    private $has_condition = false;
    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.ReturnContent return_content = 4;</code>
     */
    private $return_content = null;
    private $has_return_content = false;
    /**
     * Generated from protobuf field <code>optional string transaction_id = 5;</code>
     */
    private $transaction_id = '';
    private $has_transaction_id = false;

    public function __construct() {
        \GPBMetadata\TableStore::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>required string table_name = 1;</code>
     * @return string
     */
    public function getTableName()
    {
        return $this->table_name;
    }

    /**
     * Generated from protobuf field <code>required string table_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTableName($var)
    {
        GPBUtil::checkString($var, True);
        $this->table_name = $var;
        $this->has_table_name = true;

        return $this;
    }

    public function hasTableName()
    {
        return $this->has_table_name;
    }

    /**
     * encoded as InplaceRowChangeSet
     *
     * Generated from protobuf field <code>required bytes row = 2;</code>
     * @return string
     */
    public function getRow()
    {
        return $this->row;
    }

    /**
     * encoded as InplaceRowChangeSet
     *
     * Generated from protobuf field <code>required bytes row = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setRow($var)
    {
        GPBUtil::checkString($var, False);
        $this->row = $var;
        $this->has_row = true;

        return $this;
    }

    public function hasRow()
    {
        return $this->has_row;
    }

    /**
     * Generated from protobuf field <code>required .aliyun.OTS.ProtoBuffer.Protocol.Condition condition = 3;</code>
     * @return \Aliyun\OTS\ProtoBuffer\Protocol\Condition
     */
    public function getCondition()
    {
        return $this->condition;
    }

    /**
     * Generated from protobuf field <code>required .aliyun.OTS.ProtoBuffer.Protocol.Condition condition = 3;</code>
     * @param \Aliyun\OTS\ProtoBuffer\Protocol\Condition $var
     * @return $this
     */
    public function setCondition($var)
    {
        GPBUtil::checkMessage($var, \Aliyun\OTS\ProtoBuffer\Protocol\Condition::class);
        $this->condition = $var;
        $this->has_condition = true;

        return $this;
    }

    public function hasCondition()
    {
        return $this->has_condition;
    }

    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.ReturnContent return_content = 4;</code>
     * @return \Aliyun\OTS\ProtoBuffer\Protocol\ReturnContent
     */
    public function getReturnContent()
    {
        return $this->return_content;
    }

    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.ReturnContent return_content = 4;</code>
     * @param \Aliyun\OTS\ProtoBuffer\Protocol\ReturnContent $var
     * @return $this
     */
    public function setReturnContent($var)
    {
        GPBUtil::checkMessage($var, \Aliyun\OTS\ProtoBuffer\Protocol\ReturnContent::class);
        $this->return_content = $var;
        $this->has_return_content = true;

        return $this;
    }

    public function hasReturnContent()
    {
        return $this->has_return_content;
    }

    /**
     * Generated from protobuf field <code>optional string transaction_id = 5;</code>
     * @return string
     */
    public function getTransactionId()
    {
        return $this->transaction_id;
    }

    /**
     * Generated from protobuf field <code>optional string transaction_id = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setTransactionId($var)
    {
        GPBUtil::checkString($var, True);
        $this->transaction_id = $var;
        $this->has_transaction_id = true;

        return $this;
    }

    public function hasTransactionId()
    {
        return $this->has_transaction_id;
    }

}

