<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table_store_search.proto

namespace Aliyun\OTS\ProtoBuffer\Protocol;

/**
 * Protobuf enum <code>Aliyun\OTS\ProtoBuffer\Protocol\QueryOperator</code>
 */
class QueryOperator
{
    /**
     * Generated from protobuf enum <code>OR = 1;</code>
     */
    const PBOR = 1;
    /**
     * Generated from protobuf enum <code>AND = 2;</code>
     */
    const PBAND = 2;
}

