<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table_store_search.proto

namespace Aliyun\OTS\ProtoBuffer\Protocol;

/**
 * Protobuf enum <code>Aliyun\OTS\ProtoBuffer\Protocol\QueryType</code>
 */
class QueryType
{
    /**
     * Generated from protobuf enum <code>MATCH_QUERY = 1;</code>
     */
    const MATCH_QUERY = 1;
    /**
     * Generated from protobuf enum <code>MATCH_PHRASE_QUERY = 2;</code>
     */
    const MATCH_PHRASE_QUERY = 2;
    /**
     * Generated from protobuf enum <code>TERM_QUERY = 3;</code>
     */
    const TERM_QUERY = 3;
    /**
     * Generated from protobuf enum <code>RANGE_QUERY = 4;</code>
     */
    const RANGE_QUERY = 4;
    /**
     * Generated from protobuf enum <code>PREFIX_QUERY = 5;</code>
     */
    const PREFIX_QUERY = 5;
    /**
     * Generated from protobuf enum <code>BOOL_QUERY = 6;</code>
     */
    const BOOL_QUERY = 6;
    /**
     * Generated from protobuf enum <code>CONST_SCORE_QUERY = 7;</code>
     */
    const CONST_SCORE_QUERY = 7;
    /**
     * Generated from protobuf enum <code>FUNCTION_SCORE_QUERY = 8;</code>
     */
    const FUNCTION_SCORE_QUERY = 8;
    /**
     * Generated from protobuf enum <code>NESTED_QUERY = 9;</code>
     */
    const NESTED_QUERY = 9;
    /**
     * Generated from protobuf enum <code>WILDCARD_QUERY = 10;</code>
     */
    const WILDCARD_QUERY = 10;
    /**
     * Generated from protobuf enum <code>MATCH_ALL_QUERY = 11;</code>
     */
    const MATCH_ALL_QUERY = 11;
    /**
     * Generated from protobuf enum <code>GEO_BOUNDING_BOX_QUERY = 12;</code>
     */
    const GEO_BOUNDING_BOX_QUERY = 12;
    /**
     * Generated from protobuf enum <code>GEO_DISTANCE_QUERY = 13;</code>
     */
    const GEO_DISTANCE_QUERY = 13;
    /**
     * Generated from protobuf enum <code>GEO_POLYGON_QUERY = 14;</code>
     */
    const GEO_POLYGON_QUERY = 14;
    /**
     * Generated from protobuf enum <code>TERMS_QUERY = 15;</code>
     */
    const TERMS_QUERY = 15;
    /**
     * Generated from protobuf enum <code>EXISTS_QUERY = 16;</code>
     */
    const EXISTS_QUERY = 16;
}

