<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table_store_search.proto

namespace Aliyun\OTS\ProtoBuffer\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>aliyun.OTS.ProtoBuffer.Protocol.Range</code>
 */
class Range extends \Aliyun\OTS\ProtoBuffer\Protocol\Message
{
    /**
     * Generated from protobuf field <code>optional double from = 1;</code>
     */
    private $from = 0.0;
    private $has_from = false;
    /**
     * Generated from protobuf field <code>optional double to = 2;</code>
     */
    private $to = 0.0;
    private $has_to = false;

    public function __construct() {
        \GPBMetadata\TableStoreSearch::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>optional double from = 1;</code>
     * @return float
     */
    public function getFrom()
    {
        return $this->from;
    }

    /**
     * Generated from protobuf field <code>optional double from = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setFrom($var)
    {
        GPBUtil::checkDouble($var);
        $this->from = $var;
        $this->has_from = true;

        return $this;
    }

    public function hasFrom()
    {
        return $this->has_from;
    }

    /**
     * Generated from protobuf field <code>optional double to = 2;</code>
     * @return float
     */
    public function getTo()
    {
        return $this->to;
    }

    /**
     * Generated from protobuf field <code>optional double to = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setTo($var)
    {
        GPBUtil::checkDouble($var);
        $this->to = $var;
        $this->has_to = true;

        return $this;
    }

    public function hasTo()
    {
        return $this->has_to;
    }

}

