<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table_store.proto

namespace Aliyun\OTS\ProtoBuffer\Protocol;

/**
 * Protobuf enum <code>Aliyun\OTS\ProtoBuffer\Protocol\RowExistenceExpectation</code>
 */
class RowExistenceExpectation
{
    /**
     * Generated from protobuf enum <code>IGNORE = 0;</code>
     */
    const IGNORE = 0;
    /**
     * Generated from protobuf enum <code>EXPECT_EXIST = 1;</code>
     */
    const EXPECT_EXIST = 1;
    /**
     * Generated from protobuf enum <code>EXPECT_NOT_EXIST = 2;</code>
     */
    const EXPECT_NOT_EXIST = 2;
}

