<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table_store.proto

namespace Aliyun\OTS\ProtoBuffer\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>aliyun.OTS.ProtoBuffer.Protocol.RowInBatchWriteRowRequest</code>
 */
class RowInBatchWriteRowRequest extends \Aliyun\OTS\ProtoBuffer\Protocol\Message
{
    /**
     * Generated from protobuf field <code>required .aliyun.OTS.ProtoBuffer.Protocol.OperationType type = 1;</code>
     */
    private $type = 0;
    private $has_type = false;
    /**
     * encoded as InplaceRowChangeSet
     *
     * Generated from protobuf field <code>required bytes row_change = 2;</code>
     */
    private $row_change = '';
    private $has_row_change = false;
    /**
     * Generated from protobuf field <code>required .aliyun.OTS.ProtoBuffer.Protocol.Condition condition = 3;</code>
     */
    private $condition = null;
    private $has_condition = false;
    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.ReturnContent return_content = 4;</code>
     */
    private $return_content = null;
    private $has_return_content = false;

    public function __construct() {
        \GPBMetadata\TableStore::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>required .aliyun.OTS.ProtoBuffer.Protocol.OperationType type = 1;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>required .aliyun.OTS.ProtoBuffer.Protocol.OperationType type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Aliyun\OTS\ProtoBuffer\Protocol\OperationType::class);
        $this->type = $var;
        $this->has_type = true;

        return $this;
    }

    public function hasType()
    {
        return $this->has_type;
    }

    /**
     * encoded as InplaceRowChangeSet
     *
     * Generated from protobuf field <code>required bytes row_change = 2;</code>
     * @return string
     */
    public function getRowChange()
    {
        return $this->row_change;
    }

    /**
     * encoded as InplaceRowChangeSet
     *
     * Generated from protobuf field <code>required bytes row_change = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setRowChange($var)
    {
        GPBUtil::checkString($var, False);
        $this->row_change = $var;
        $this->has_row_change = true;

        return $this;
    }

    public function hasRowChange()
    {
        return $this->has_row_change;
    }

    /**
     * Generated from protobuf field <code>required .aliyun.OTS.ProtoBuffer.Protocol.Condition condition = 3;</code>
     * @return \Aliyun\OTS\ProtoBuffer\Protocol\Condition
     */
    public function getCondition()
    {
        return $this->condition;
    }

    /**
     * Generated from protobuf field <code>required .aliyun.OTS.ProtoBuffer.Protocol.Condition condition = 3;</code>
     * @param \Aliyun\OTS\ProtoBuffer\Protocol\Condition $var
     * @return $this
     */
    public function setCondition($var)
    {
        GPBUtil::checkMessage($var, \Aliyun\OTS\ProtoBuffer\Protocol\Condition::class);
        $this->condition = $var;
        $this->has_condition = true;

        return $this;
    }

    public function hasCondition()
    {
        return $this->has_condition;
    }

    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.ReturnContent return_content = 4;</code>
     * @return \Aliyun\OTS\ProtoBuffer\Protocol\ReturnContent
     */
    public function getReturnContent()
    {
        return $this->return_content;
    }

    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.ReturnContent return_content = 4;</code>
     * @param \Aliyun\OTS\ProtoBuffer\Protocol\ReturnContent $var
     * @return $this
     */
    public function setReturnContent($var)
    {
        GPBUtil::checkMessage($var, \Aliyun\OTS\ProtoBuffer\Protocol\ReturnContent::class);
        $this->return_content = $var;
        $this->has_return_content = true;

        return $this;
    }

    public function hasReturnContent()
    {
        return $this->has_return_content;
    }

}

