<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table_store_search.proto

namespace Aliyun\OTS\ProtoBuffer\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>aliyun.OTS.ProtoBuffer.Protocol.SearchRequest</code>
 */
class SearchRequest extends \Aliyun\OTS\ProtoBuffer\Protocol\Message
{
    /**
     * Generated from protobuf field <code>optional string table_name = 1;</code>
     */
    private $table_name = '';
    private $has_table_name = false;
    /**
     * Generated from protobuf field <code>optional string index_name = 2;</code>
     */
    private $index_name = '';
    private $has_index_name = false;
    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.ColumnsToGet columns_to_get = 3;</code>
     */
    private $columns_to_get = null;
    private $has_columns_to_get = false;
    /**
     * Generated from protobuf field <code>optional bytes search_query = 4;</code>
     */
    private $search_query = '';
    private $has_search_query = false;
    /**
     * Generated from protobuf field <code>repeated bytes routing_values = 5;</code>
     */
    private $routing_values;
    private $has_routing_values = false;
    /**
     * Generated from protobuf field <code>optional int32 timeout_ms = 6;</code>
     */
    private $timeout_ms = 0;
    private $has_timeout_ms = false;

    public function __construct() {
        \GPBMetadata\TableStoreSearch::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>optional string table_name = 1;</code>
     * @return string
     */
    public function getTableName()
    {
        return $this->table_name;
    }

    /**
     * Generated from protobuf field <code>optional string table_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTableName($var)
    {
        GPBUtil::checkString($var, True);
        $this->table_name = $var;
        $this->has_table_name = true;

        return $this;
    }

    public function hasTableName()
    {
        return $this->has_table_name;
    }

    /**
     * Generated from protobuf field <code>optional string index_name = 2;</code>
     * @return string
     */
    public function getIndexName()
    {
        return $this->index_name;
    }

    /**
     * Generated from protobuf field <code>optional string index_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setIndexName($var)
    {
        GPBUtil::checkString($var, True);
        $this->index_name = $var;
        $this->has_index_name = true;

        return $this;
    }

    public function hasIndexName()
    {
        return $this->has_index_name;
    }

    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.ColumnsToGet columns_to_get = 3;</code>
     * @return \Aliyun\OTS\ProtoBuffer\Protocol\ColumnsToGet
     */
    public function getColumnsToGet()
    {
        return $this->columns_to_get;
    }

    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.ColumnsToGet columns_to_get = 3;</code>
     * @param \Aliyun\OTS\ProtoBuffer\Protocol\ColumnsToGet $var
     * @return $this
     */
    public function setColumnsToGet($var)
    {
        GPBUtil::checkMessage($var, \Aliyun\OTS\ProtoBuffer\Protocol\ColumnsToGet::class);
        $this->columns_to_get = $var;
        $this->has_columns_to_get = true;

        return $this;
    }

    public function hasColumnsToGet()
    {
        return $this->has_columns_to_get;
    }

    /**
     * Generated from protobuf field <code>optional bytes search_query = 4;</code>
     * @return string
     */
    public function getSearchQuery()
    {
        return $this->search_query;
    }

    /**
     * Generated from protobuf field <code>optional bytes search_query = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setSearchQuery($var)
    {
        GPBUtil::checkString($var, False);
        $this->search_query = $var;
        $this->has_search_query = true;

        return $this;
    }

    public function hasSearchQuery()
    {
        return $this->has_search_query;
    }

    /**
     * Generated from protobuf field <code>repeated bytes routing_values = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRoutingValues()
    {
        return $this->routing_values;
    }

    /**
     * Generated from protobuf field <code>repeated bytes routing_values = 5;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRoutingValues($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->routing_values = $arr;
        $this->has_routing_values = true;

        return $this;
    }

    public function hasRoutingValues()
    {
        return $this->has_routing_values;
    }

    /**
     * Generated from protobuf field <code>optional int32 timeout_ms = 6;</code>
     * @return int
     */
    public function getTimeoutMs()
    {
        return $this->timeout_ms;
    }

    /**
     * Generated from protobuf field <code>optional int32 timeout_ms = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setTimeoutMs($var)
    {
        GPBUtil::checkInt32($var);
        $this->timeout_ms = $var;
        $this->has_timeout_ms = true;

        return $this;
    }

    public function hasTimeoutMs()
    {
        return $this->has_timeout_ms;
    }

}

