<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table_store_search.proto

namespace Aliyun\OTS\ProtoBuffer\Protocol;

/**
 * Protobuf enum <code>Aliyun\OTS\ProtoBuffer\Protocol\SortOrder</code>
 */
class SortOrder
{
    /**
     * Generated from protobuf enum <code>SORT_ORDER_ASC = 0;</code>
     */
    const SORT_ORDER_ASC = 0;
    /**
     * Generated from protobuf enum <code>SORT_ORDER_DESC = 1;</code>
     */
    const SORT_ORDER_DESC = 1;
}

