<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table_store_search.proto

namespace Aliyun\OTS\ProtoBuffer\Protocol;

/**
 * Protobuf enum <code>Aliyun\OTS\ProtoBuffer\Protocol\SortMode</code>
 */
class SortMode
{
    /**
     * Generated from protobuf enum <code>SORT_MODE_MIN = 0;</code>
     */
    const SORT_MODE_MIN = 0;
    /**
     * Generated from protobuf enum <code>SORT_MODE_MAX = 1;</code>
     */
    const SORT_MODE_MAX = 1;
    /**
     * Generated from protobuf enum <code>SORT_MODE_AVG = 2;</code>
     */
    const SORT_MODE_AVG = 2;
}

