<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table_store_search.proto

namespace Aliyun\OTS\ProtoBuffer\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>aliyun.OTS.ProtoBuffer.Protocol.Sort</code>
 */
class Sort extends \Aliyun\OTS\ProtoBuffer\Protocol\Message
{
    /**
     * Generated from protobuf field <code>repeated .aliyun.OTS.ProtoBuffer.Protocol.Sorter sorter = 1;</code>
     */
    private $sorter;
    private $has_sorter = false;

    public function __construct() {
        \GPBMetadata\TableStoreSearch::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>repeated .aliyun.OTS.ProtoBuffer.Protocol.Sorter sorter = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSorter()
    {
        return $this->sorter;
    }

    /**
     * Generated from protobuf field <code>repeated .aliyun.OTS.ProtoBuffer.Protocol.Sorter sorter = 1;</code>
     * @param \Aliyun\OTS\ProtoBuffer\Protocol\Sorter[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSorter($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Aliyun\OTS\ProtoBuffer\Protocol\Sorter::class);
        $this->sorter = $arr;
        $this->has_sorter = true;

        return $this;
    }

    public function hasSorter()
    {
        return $this->has_sorter;
    }

}

