<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table_store.proto

namespace Aliyun\OTS\ProtoBuffer\Protocol;

/**
 * SQLQuery 
 *
 * Protobuf enum <code>Aliyun\OTS\ProtoBuffer\Protocol\SQLPayloadVersion</code>
 */
class SQLPayloadVersion
{
    /**
     * Generated from protobuf enum <code>SQL_PLAIN_BUFFER = 1;</code>
     */
    const SQL_PLAIN_BUFFER = 1;
    /**
     * Generated from protobuf enum <code>SQL_FLAT_BUFFERS = 2;</code>
     */
    const SQL_FLAT_BUFFERS = 2;
}

