<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table_store.proto

namespace Aliyun\OTS\ProtoBuffer\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>aliyun.OTS.ProtoBuffer.Protocol.SQLQueryResponse</code>
 */
class SQLQueryResponse extends \Aliyun\OTS\ProtoBuffer\Protocol\Message
{
    /**
     * Generated from protobuf field <code>repeated .aliyun.OTS.ProtoBuffer.Protocol.TableConsumedCapacity consumes = 1;</code>
     */
    private $consumes;
    private $has_consumes = false;
    /**
     * Generated from protobuf field <code>optional bytes rows = 2;</code>
     */
    private $rows = '';
    private $has_rows = false;
    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.SQLPayloadVersion version = 3;</code>
     */
    private $version = 0;
    private $has_version = false;
    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.SQLStatementType type = 4;</code>
     */
    private $type = 0;
    private $has_type = false;
    /**
     * Generated from protobuf field <code>repeated .aliyun.OTS.ProtoBuffer.Protocol.SearchConsumedCapacity search_consumes = 5;</code>
     */
    private $search_consumes;
    private $has_search_consumes = false;

    public function __construct() {
        \GPBMetadata\TableStore::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>repeated .aliyun.OTS.ProtoBuffer.Protocol.TableConsumedCapacity consumes = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getConsumes()
    {
        return $this->consumes;
    }

    /**
     * Generated from protobuf field <code>repeated .aliyun.OTS.ProtoBuffer.Protocol.TableConsumedCapacity consumes = 1;</code>
     * @param \Aliyun\OTS\ProtoBuffer\Protocol\TableConsumedCapacity[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setConsumes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Aliyun\OTS\ProtoBuffer\Protocol\TableConsumedCapacity::class);
        $this->consumes = $arr;
        $this->has_consumes = true;

        return $this;
    }

    public function hasConsumes()
    {
        return $this->has_consumes;
    }

    /**
     * Generated from protobuf field <code>optional bytes rows = 2;</code>
     * @return string
     */
    public function getRows()
    {
        return $this->rows;
    }

    /**
     * Generated from protobuf field <code>optional bytes rows = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setRows($var)
    {
        GPBUtil::checkString($var, False);
        $this->rows = $var;
        $this->has_rows = true;

        return $this;
    }

    public function hasRows()
    {
        return $this->has_rows;
    }

    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.SQLPayloadVersion version = 3;</code>
     * @return int
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.SQLPayloadVersion version = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkEnum($var, \Aliyun\OTS\ProtoBuffer\Protocol\SQLPayloadVersion::class);
        $this->version = $var;
        $this->has_version = true;

        return $this;
    }

    public function hasVersion()
    {
        return $this->has_version;
    }

    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.SQLStatementType type = 4;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.SQLStatementType type = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Aliyun\OTS\ProtoBuffer\Protocol\SQLStatementType::class);
        $this->type = $var;
        $this->has_type = true;

        return $this;
    }

    public function hasType()
    {
        return $this->has_type;
    }

    /**
     * Generated from protobuf field <code>repeated .aliyun.OTS.ProtoBuffer.Protocol.SearchConsumedCapacity search_consumes = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSearchConsumes()
    {
        return $this->search_consumes;
    }

    /**
     * Generated from protobuf field <code>repeated .aliyun.OTS.ProtoBuffer.Protocol.SearchConsumedCapacity search_consumes = 5;</code>
     * @param \Aliyun\OTS\ProtoBuffer\Protocol\SearchConsumedCapacity[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSearchConsumes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Aliyun\OTS\ProtoBuffer\Protocol\SearchConsumedCapacity::class);
        $this->search_consumes = $arr;
        $this->has_search_consumes = true;

        return $this;
    }

    public function hasSearchConsumes()
    {
        return $this->has_search_consumes;
    }

}

