<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table_store.proto

namespace Aliyun\OTS\ProtoBuffer\Protocol;

/**
 * Protobuf enum <code>Aliyun\OTS\ProtoBuffer\Protocol\SQLStatementType</code>
 */
class SQLStatementType
{
    /**
     * Generated from protobuf enum <code>SQL_SELECT = 1;</code>
     */
    const SQL_SELECT = 1;
    /**
     * Generated from protobuf enum <code>SQL_CREATE_TABLE = 2;</code>
     */
    const SQL_CREATE_TABLE = 2;
    /**
     * Generated from protobuf enum <code>SQL_SHOW_TABLE = 3;</code>
     */
    const SQL_SHOW_TABLE = 3;
    /**
     * Generated from protobuf enum <code>SQL_DESCRIBE_TABLE = 4;</code>
     */
    const SQL_DESCRIBE_TABLE = 4;
    /**
     * Generated from protobuf enum <code>SQL_DROP_TABLE = 5;</code>
     */
    const SQL_DROP_TABLE = 5;
    /**
     * Generated from protobuf enum <code>SQL_ALTER_TABLE = 6;</code>
     */
    const SQL_ALTER_TABLE = 6;
}

