<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table_store.proto

namespace Aliyun\OTS\ProtoBuffer\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>aliyun.OTS.ProtoBuffer.Protocol.StreamShard</code>
 */
class StreamShard extends \Aliyun\OTS\ProtoBuffer\Protocol\Message
{
    /**
     * Generated from protobuf field <code>required string shard_id = 1;</code>
     */
    private $shard_id = '';
    private $has_shard_id = false;
    /**
     * Generated from protobuf field <code>optional string parent_id = 2;</code>
     */
    private $parent_id = '';
    private $has_parent_id = false;
    /**
     * Generated from protobuf field <code>optional string parent_sibling_id = 3;</code>
     */
    private $parent_sibling_id = '';
    private $has_parent_sibling_id = false;

    public function __construct() {
        \GPBMetadata\TableStore::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>required string shard_id = 1;</code>
     * @return string
     */
    public function getShardId()
    {
        return $this->shard_id;
    }

    /**
     * Generated from protobuf field <code>required string shard_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setShardId($var)
    {
        GPBUtil::checkString($var, True);
        $this->shard_id = $var;
        $this->has_shard_id = true;

        return $this;
    }

    public function hasShardId()
    {
        return $this->has_shard_id;
    }

    /**
     * Generated from protobuf field <code>optional string parent_id = 2;</code>
     * @return string
     */
    public function getParentId()
    {
        return $this->parent_id;
    }

    /**
     * Generated from protobuf field <code>optional string parent_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setParentId($var)
    {
        GPBUtil::checkString($var, True);
        $this->parent_id = $var;
        $this->has_parent_id = true;

        return $this;
    }

    public function hasParentId()
    {
        return $this->has_parent_id;
    }

    /**
     * Generated from protobuf field <code>optional string parent_sibling_id = 3;</code>
     * @return string
     */
    public function getParentSiblingId()
    {
        return $this->parent_sibling_id;
    }

    /**
     * Generated from protobuf field <code>optional string parent_sibling_id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setParentSiblingId($var)
    {
        GPBUtil::checkString($var, True);
        $this->parent_sibling_id = $var;
        $this->has_parent_sibling_id = true;

        return $this;
    }

    public function hasParentSiblingId()
    {
        return $this->has_parent_sibling_id;
    }

}

