<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table_store_search.proto

namespace Aliyun\OTS\ProtoBuffer\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>aliyun.OTS.ProtoBuffer.Protocol.SyncStat</code>
 */
class SyncStat extends \Aliyun\OTS\ProtoBuffer\Protocol\Message
{
    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.SyncPhase sync_phase = 1;</code>
     */
    private $sync_phase = 0;
    private $has_sync_phase = false;
    /**
     * 同步进度，参考TunnelService。
     *
     * Generated from protobuf field <code>optional int64 current_sync_timestamp = 2;</code>
     */
    private $current_sync_timestamp = 0;
    private $has_current_sync_timestamp = false;

    public function __construct() {
        \GPBMetadata\TableStoreSearch::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.SyncPhase sync_phase = 1;</code>
     * @return int
     */
    public function getSyncPhase()
    {
        return $this->sync_phase;
    }

    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.SyncPhase sync_phase = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setSyncPhase($var)
    {
        GPBUtil::checkEnum($var, \Aliyun\OTS\ProtoBuffer\Protocol\SyncPhase::class);
        $this->sync_phase = $var;
        $this->has_sync_phase = true;

        return $this;
    }

    public function hasSyncPhase()
    {
        return $this->has_sync_phase;
    }

    /**
     * 同步进度，参考TunnelService。
     *
     * Generated from protobuf field <code>optional int64 current_sync_timestamp = 2;</code>
     * @return int|string
     */
    public function getCurrentSyncTimestamp()
    {
        return $this->current_sync_timestamp;
    }

    /**
     * 同步进度，参考TunnelService。
     *
     * Generated from protobuf field <code>optional int64 current_sync_timestamp = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCurrentSyncTimestamp($var)
    {
        GPBUtil::checkInt64($var);
        $this->current_sync_timestamp = $var;
        $this->has_current_sync_timestamp = true;

        return $this;
    }

    public function hasCurrentSyncTimestamp()
    {
        return $this->has_current_sync_timestamp;
    }

}

