<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table_store.proto

namespace Aliyun\OTS\ProtoBuffer\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>aliyun.OTS.ProtoBuffer.Protocol.TableOptions</code>
 */
class TableOptions extends \Aliyun\OTS\ProtoBuffer\Protocol\Message
{
    /**
     * 数据生命周期,可以动态更改
     *
     * Generated from protobuf field <code>optional int32 time_to_live = 1;</code>
     */
    private $time_to_live = 0;
    private $has_time_to_live = false;
    /**
     * 最大数据版本,可以动态更改
     *
     * Generated from protobuf field <code>optional int32 max_versions = 2;</code>
     */
    private $max_versions = 0;
    private $has_max_versions = false;
    /**
     * 数据有效版本偏差,可以动态修改
     *
     * Generated from protobuf field <code>optional int64 deviation_cell_version_in_sec = 5;</code>
     */
    private $deviation_cell_version_in_sec = 0;
    private $has_deviation_cell_version_in_sec = false;

    public function __construct() {
        \GPBMetadata\TableStore::initOnce();
        parent::__construct();
    }

    /**
     * 数据生命周期,可以动态更改
     *
     * Generated from protobuf field <code>optional int32 time_to_live = 1;</code>
     * @return int
     */
    public function getTimeToLive()
    {
        return $this->time_to_live;
    }

    /**
     * 数据生命周期,可以动态更改
     *
     * Generated from protobuf field <code>optional int32 time_to_live = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setTimeToLive($var)
    {
        GPBUtil::checkInt32($var);
        $this->time_to_live = $var;
        $this->has_time_to_live = true;

        return $this;
    }

    public function hasTimeToLive()
    {
        return $this->has_time_to_live;
    }

    /**
     * 最大数据版本,可以动态更改
     *
     * Generated from protobuf field <code>optional int32 max_versions = 2;</code>
     * @return int
     */
    public function getMaxVersions()
    {
        return $this->max_versions;
    }

    /**
     * 最大数据版本,可以动态更改
     *
     * Generated from protobuf field <code>optional int32 max_versions = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setMaxVersions($var)
    {
        GPBUtil::checkInt32($var);
        $this->max_versions = $var;
        $this->has_max_versions = true;

        return $this;
    }

    public function hasMaxVersions()
    {
        return $this->has_max_versions;
    }

    /**
     * 数据有效版本偏差,可以动态修改
     *
     * Generated from protobuf field <code>optional int64 deviation_cell_version_in_sec = 5;</code>
     * @return int|string
     */
    public function getDeviationCellVersionInSec()
    {
        return $this->deviation_cell_version_in_sec;
    }

    /**
     * 数据有效版本偏差,可以动态修改
     *
     * Generated from protobuf field <code>optional int64 deviation_cell_version_in_sec = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDeviationCellVersionInSec($var)
    {
        GPBUtil::checkInt64($var);
        $this->deviation_cell_version_in_sec = $var;
        $this->has_deviation_cell_version_in_sec = true;

        return $this;
    }

    public function hasDeviationCellVersionInSec()
    {
        return $this->has_deviation_cell_version_in_sec;
    }

}

