<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table_store.proto

namespace Aliyun\OTS\ProtoBuffer\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>aliyun.OTS.ProtoBuffer.Protocol.TableOptions</code>
 */
class TableOptions extends \Aliyun\OTS\ProtoBuffer\Protocol\Message
{
    /**
     * 可以动态更改
     *
     * Generated from protobuf field <code>optional int32 time_to_live = 1;</code>
     */
    private $time_to_live = 0;
    private $has_time_to_live = false;
    /**
     * 可以动态更改
     *
     * Generated from protobuf field <code>optional int32 max_versions = 2;</code>
     */
    private $max_versions = 0;
    private $has_max_versions = false;
    /**
     * 可以动态更改
     *
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.BloomFilterType bloom_filter_type = 3;</code>
     */
    private $bloom_filter_type = 0;
    private $has_bloom_filter_type = false;
    /**
     * 可以动态更改
     *
     * Generated from protobuf field <code>optional int32 block_size = 4;</code>
     */
    private $block_size = 0;
    private $has_block_size = false;
    /**
     * 可以动态修改
     *
     * Generated from protobuf field <code>optional int64 deviation_cell_version_in_sec = 5;</code>
     */
    private $deviation_cell_version_in_sec = 0;
    private $has_deviation_cell_version_in_sec = false;
    /**
     * Generated from protobuf field <code>optional bool allow_update = 6;</code>
     */
    private $allow_update = false;
    private $has_allow_update = false;

    public function __construct() {
        \GPBMetadata\TableStore::initOnce();
        parent::__construct();
    }

    /**
     * 可以动态更改
     *
     * Generated from protobuf field <code>optional int32 time_to_live = 1;</code>
     * @return int
     */
    public function getTimeToLive()
    {
        return $this->time_to_live;
    }

    /**
     * 可以动态更改
     *
     * Generated from protobuf field <code>optional int32 time_to_live = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setTimeToLive($var)
    {
        GPBUtil::checkInt32($var);
        $this->time_to_live = $var;
        $this->has_time_to_live = true;

        return $this;
    }

    public function hasTimeToLive()
    {
        return $this->has_time_to_live;
    }

    /**
     * 可以动态更改
     *
     * Generated from protobuf field <code>optional int32 max_versions = 2;</code>
     * @return int
     */
    public function getMaxVersions()
    {
        return $this->max_versions;
    }

    /**
     * 可以动态更改
     *
     * Generated from protobuf field <code>optional int32 max_versions = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setMaxVersions($var)
    {
        GPBUtil::checkInt32($var);
        $this->max_versions = $var;
        $this->has_max_versions = true;

        return $this;
    }

    public function hasMaxVersions()
    {
        return $this->has_max_versions;
    }

    /**
     * 可以动态更改
     *
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.BloomFilterType bloom_filter_type = 3;</code>
     * @return int
     */
    public function getBloomFilterType()
    {
        return $this->bloom_filter_type;
    }

    /**
     * 可以动态更改
     *
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.BloomFilterType bloom_filter_type = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setBloomFilterType($var)
    {
        GPBUtil::checkEnum($var, \Aliyun\OTS\ProtoBuffer\Protocol\BloomFilterType::class);
        $this->bloom_filter_type = $var;
        $this->has_bloom_filter_type = true;

        return $this;
    }

    public function hasBloomFilterType()
    {
        return $this->has_bloom_filter_type;
    }

    /**
     * 可以动态更改
     *
     * Generated from protobuf field <code>optional int32 block_size = 4;</code>
     * @return int
     */
    public function getBlockSize()
    {
        return $this->block_size;
    }

    /**
     * 可以动态更改
     *
     * Generated from protobuf field <code>optional int32 block_size = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setBlockSize($var)
    {
        GPBUtil::checkInt32($var);
        $this->block_size = $var;
        $this->has_block_size = true;

        return $this;
    }

    public function hasBlockSize()
    {
        return $this->has_block_size;
    }

    /**
     * 可以动态修改
     *
     * Generated from protobuf field <code>optional int64 deviation_cell_version_in_sec = 5;</code>
     * @return int|string
     */
    public function getDeviationCellVersionInSec()
    {
        return $this->deviation_cell_version_in_sec;
    }

    /**
     * 可以动态修改
     *
     * Generated from protobuf field <code>optional int64 deviation_cell_version_in_sec = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDeviationCellVersionInSec($var)
    {
        GPBUtil::checkInt64($var);
        $this->deviation_cell_version_in_sec = $var;
        $this->has_deviation_cell_version_in_sec = true;

        return $this;
    }

    public function hasDeviationCellVersionInSec()
    {
        return $this->has_deviation_cell_version_in_sec;
    }

    /**
     * Generated from protobuf field <code>optional bool allow_update = 6;</code>
     * @return bool
     */
    public function getAllowUpdate()
    {
        return $this->allow_update;
    }

    /**
     * Generated from protobuf field <code>optional bool allow_update = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setAllowUpdate($var)
    {
        GPBUtil::checkBool($var);
        $this->allow_update = $var;
        $this->has_allow_update = true;

        return $this;
    }

    public function hasAllowUpdate()
    {
        return $this->has_allow_update;
    }

}

