<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table_store.proto

namespace Aliyun\OTS\ProtoBuffer\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>aliyun.OTS.ProtoBuffer.Protocol.UpdateTableResponse</code>
 */
class UpdateTableResponse extends \Aliyun\OTS\ProtoBuffer\Protocol\Message
{
    /**
     * Generated from protobuf field <code>required .aliyun.OTS.ProtoBuffer.Protocol.ReservedThroughputDetails reserved_throughput_details = 1;</code>
     */
    private $reserved_throughput_details = null;
    private $has_reserved_throughput_details = false;
    /**
     * Generated from protobuf field <code>required .aliyun.OTS.ProtoBuffer.Protocol.TableOptions table_options = 2;</code>
     */
    private $table_options = null;
    private $has_table_options = false;
    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.StreamDetails stream_details = 3;</code>
     */
    private $stream_details = null;
    private $has_stream_details = false;

    public function __construct() {
        \GPBMetadata\TableStore::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>required .aliyun.OTS.ProtoBuffer.Protocol.ReservedThroughputDetails reserved_throughput_details = 1;</code>
     * @return \Aliyun\OTS\ProtoBuffer\Protocol\ReservedThroughputDetails
     */
    public function getReservedThroughputDetails()
    {
        return $this->reserved_throughput_details;
    }

    /**
     * Generated from protobuf field <code>required .aliyun.OTS.ProtoBuffer.Protocol.ReservedThroughputDetails reserved_throughput_details = 1;</code>
     * @param \Aliyun\OTS\ProtoBuffer\Protocol\ReservedThroughputDetails $var
     * @return $this
     */
    public function setReservedThroughputDetails($var)
    {
        GPBUtil::checkMessage($var, \Aliyun\OTS\ProtoBuffer\Protocol\ReservedThroughputDetails::class);
        $this->reserved_throughput_details = $var;
        $this->has_reserved_throughput_details = true;

        return $this;
    }

    public function hasReservedThroughputDetails()
    {
        return $this->has_reserved_throughput_details;
    }

    /**
     * Generated from protobuf field <code>required .aliyun.OTS.ProtoBuffer.Protocol.TableOptions table_options = 2;</code>
     * @return \Aliyun\OTS\ProtoBuffer\Protocol\TableOptions
     */
    public function getTableOptions()
    {
        return $this->table_options;
    }

    /**
     * Generated from protobuf field <code>required .aliyun.OTS.ProtoBuffer.Protocol.TableOptions table_options = 2;</code>
     * @param \Aliyun\OTS\ProtoBuffer\Protocol\TableOptions $var
     * @return $this
     */
    public function setTableOptions($var)
    {
        GPBUtil::checkMessage($var, \Aliyun\OTS\ProtoBuffer\Protocol\TableOptions::class);
        $this->table_options = $var;
        $this->has_table_options = true;

        return $this;
    }

    public function hasTableOptions()
    {
        return $this->has_table_options;
    }

    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.StreamDetails stream_details = 3;</code>
     * @return \Aliyun\OTS\ProtoBuffer\Protocol\StreamDetails
     */
    public function getStreamDetails()
    {
        return $this->stream_details;
    }

    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.StreamDetails stream_details = 3;</code>
     * @param \Aliyun\OTS\ProtoBuffer\Protocol\StreamDetails $var
     * @return $this
     */
    public function setStreamDetails($var)
    {
        GPBUtil::checkMessage($var, \Aliyun\OTS\ProtoBuffer\Protocol\StreamDetails::class);
        $this->stream_details = $var;
        $this->has_stream_details = true;

        return $this;
    }

    public function hasStreamDetails()
    {
        return $this->has_stream_details;
    }

}

