<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table_store.proto

namespace Aliyun\OTS\ProtoBuffer\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>aliyun.OTS.ProtoBuffer.Protocol.UpdateRowResponse</code>
 */
class UpdateRowResponse extends \Aliyun\OTS\ProtoBuffer\Protocol\Message
{
    /**
     * Generated from protobuf field <code>required .aliyun.OTS.ProtoBuffer.Protocol.ConsumedCapacity consumed = 1;</code>
     */
    private $consumed = null;
    private $has_consumed = false;
    /**
     * Generated from protobuf field <code>optional bytes row = 2;</code>
     */
    private $row = '';
    private $has_row = false;

    public function __construct() {
        \GPBMetadata\TableStore::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>required .aliyun.OTS.ProtoBuffer.Protocol.ConsumedCapacity consumed = 1;</code>
     * @return \Aliyun\OTS\ProtoBuffer\Protocol\ConsumedCapacity
     */
    public function getConsumed()
    {
        return $this->consumed;
    }

    /**
     * Generated from protobuf field <code>required .aliyun.OTS.ProtoBuffer.Protocol.ConsumedCapacity consumed = 1;</code>
     * @param \Aliyun\OTS\ProtoBuffer\Protocol\ConsumedCapacity $var
     * @return $this
     */
    public function setConsumed($var)
    {
        GPBUtil::checkMessage($var, \Aliyun\OTS\ProtoBuffer\Protocol\ConsumedCapacity::class);
        $this->consumed = $var;
        $this->has_consumed = true;

        return $this;
    }

    public function hasConsumed()
    {
        return $this->has_consumed;
    }

    /**
     * Generated from protobuf field <code>optional bytes row = 2;</code>
     * @return string
     */
    public function getRow()
    {
        return $this->row;
    }

    /**
     * Generated from protobuf field <code>optional bytes row = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setRow($var)
    {
        GPBUtil::checkString($var, False);
        $this->row = $var;
        $this->has_row = true;

        return $this;
    }

    public function hasRow()
    {
        return $this->has_row;
    }

}

