<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table_store_search.proto

namespace Aliyun\OTS\ProtoBuffer\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>aliyun.OTS.ProtoBuffer.Protocol.VectorOptions</code>
 */
class VectorOptions extends \Aliyun\OTS\ProtoBuffer\Protocol\Message
{
    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.VectorDataType data_type = 1;</code>
     */
    private $data_type = 0;
    private $has_data_type = false;
    /**
     * Generated from protobuf field <code>optional int32 dimension = 2;</code>
     */
    private $dimension = 0;
    private $has_dimension = false;
    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.VectorMetricType metric_type = 3;</code>
     */
    private $metric_type = 0;
    private $has_metric_type = false;

    public function __construct() {
        \GPBMetadata\TableStoreSearch::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.VectorDataType data_type = 1;</code>
     * @return int
     */
    public function getDataType()
    {
        return $this->data_type;
    }

    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.VectorDataType data_type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setDataType($var)
    {
        GPBUtil::checkEnum($var, \Aliyun\OTS\ProtoBuffer\Protocol\VectorDataType::class);
        $this->data_type = $var;
        $this->has_data_type = true;

        return $this;
    }

    public function hasDataType()
    {
        return $this->has_data_type;
    }

    /**
     * Generated from protobuf field <code>optional int32 dimension = 2;</code>
     * @return int
     */
    public function getDimension()
    {
        return $this->dimension;
    }

    /**
     * Generated from protobuf field <code>optional int32 dimension = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setDimension($var)
    {
        GPBUtil::checkInt32($var);
        $this->dimension = $var;
        $this->has_dimension = true;

        return $this;
    }

    public function hasDimension()
    {
        return $this->has_dimension;
    }

    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.VectorMetricType metric_type = 3;</code>
     * @return int
     */
    public function getMetricType()
    {
        return $this->metric_type;
    }

    /**
     * Generated from protobuf field <code>optional .aliyun.OTS.ProtoBuffer.Protocol.VectorMetricType metric_type = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setMetricType($var)
    {
        GPBUtil::checkEnum($var, \Aliyun\OTS\ProtoBuffer\Protocol\VectorMetricType::class);
        $this->metric_type = $var;
        $this->has_metric_type = true;

        return $this;
    }

    public function hasMetricType()
    {
        return $this->has_metric_type;
    }

}

